Factor out test helpers from go_router_test
flutter/packages pull request #2312
Opened 2022-07-08 16:40 UTC by guidezpl

This is to avoid having to import from a test file for `error_scheen_helpers.dart`.

2022-07-11 16:31 UTC, stuartmorgan requested changes

2022-07-11 16:31 UTC, stuartmorgan commented on packages/go_router/pubspec.yaml
> +version: 4.1.1
Test-only changes shouldn't change the version.

2022-07-11 18:05 UTC, stuartmorgan commented
FYI it's fine to take the "No CHANGELOG change:" PR description annotation approach in this PR (rather than doing a `## NEXT` CHANGELOG entry).

2022-07-12 18:22 UTC, johnpryan approved these changes
Thanks!

2022-07-12 18:23 UTC, guidezpl commented
Do I have to do something for the publishable check to update?

2022-07-12 18:26 UTC, johnpryan commented
IIRC it will pass when it's merged into `main`

2022-07-12 18:39 UTC, stuartmorgan commented
> Do I have to do something for the publishable check to update?

Usually pushing a new commit does it; I'm not sure why it didn't here. Maybe empty commits don't work? (Unfortunately I don't know where the caching of the PR description our script receives is happening or why; it's not part of our pipeline.)

I would try either a merge or rebase from `main`, or an amend commit that changes the commit message slightly combined with a force-push.

2022-07-12 18:39 UTC, stuartmorgan commented
> IIRC it will pass when it's merged into `main`

Checks with failing presubmits shouldn't be merged to `main`.

2022-07-12 18:48 UTC, stuartmorgan commented
I have no idea why it's still failing; it definitely shouldn't be. Feel free to land manually, and I'll file an issue to try to repro this with instrumented tooling.

2022-07-12 19:01 UTC, guidezpl commented
I think you need to approve first 
![image](https://user-images.githubusercontent.com/6655696/178573628-b2382d5c-e983-4083-b89d-faa37058ae77.png)

2022-07-13 19:32 UTC, merged