[pigeon] Handle int results from Flutter as Integer or Long.
flutter/packages pull request #2324
Opened 2022-07-14 19:47 UTC by romkal

Current int results are cast to Long. This fails when the result fits in Integer
as this is what gets returned and causes ClassCastException.

This PR handles responses as Numbers and gets their long value instead.

Issue: https://github.com/flutter/flutter/issues/87307

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-07-25 20:47 UTC, prince-kumar reviewed
LGTM

2022-07-26 21:34 UTC, gaaclarke requested changes
Awesome patch, thanks.  LGTM modulo a description edit.

My only criticism is that it took me a while to make sure I understood the problem it fixes.  Filing an issue with reproduction code can make this easier to communicate.  I know this is particularly difficult to talk to since it operates at a meta level.

2022-07-26 21:34 UTC, gaaclarke commented on packages/pigeon/CHANGELOG.md
> +* [java] Correctly handles int results that are sent as java Integer.
```suggestion
* [java] Fixes returning int values from FlutterApi methods that fit in 32 bits.
```

2022-07-27 18:34 UTC, gaaclarke approved these changes

2022-07-27 18:36 UTC, merged