Sync lints
flutter/packages pull request #2495
Opened 2022-08-23 23:53 UTC by goderbauer

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-08-24 16:50 UTC, goderbauer commented
@stuartmorgan Is there anything special I need to do for packages that have a "NEXT" changelog entry? The check is not happy with what I did: https://cirrus-ci.com/task/5907580605169664

2022-08-24 17:01 UTC, stuartmorgan requested changes
Thanks, this has been on my TODO list for quite a while!

Just some small things here and there.

2022-08-24 17:01 UTC, stuartmorgan commented on packages/standard_message_codec/example/lib/readme_excerpts.dart
> +  print('The encoded message is $data'); // ignore: avoid_print
This should be at the file level so this doesn't show up in the excerpt (once the excerpt annotations are fixed).

2022-08-24 17:02 UTC, stuartmorgan commented
> @stuartmorgan Is there anything special I need to do for packages that have a "NEXT" changelog entry? The check is not happy with what I did: https://cirrus-ci.com/task/5907580605169664

You can't use `NEXT` if you are changing client-affecting code without overriding the check, because of [repo policy](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version). If there are cases you are absolutely sure shouldn't be versioned, we can override them, but at least some of them should be.

2022-08-24 23:17 UTC, goderbauer commented
This is ready for another review.

For the packages `cross_file` and `standard_message_codec` I'd like to get an exception for versioning and changeloging as there are no meaningful changes to production code to these two packages.

2022-08-25 14:54 UTC, stuartmorgan approved these changes
LGTM with nit. Thanks again!

2022-08-25 14:54 UTC, stuartmorgan commented on packages/cross_file/CHANGELOG.md
> +* Fixed lint warnings in tests.
Nit: Fixes

Per style guide.

2022-08-25 14:54 UTC, stuartmorgan commented on packages/standard_message_codec/CHANGELOG.md
> +* Fixed lint warnings.
Same.

2022-08-25 16:57 UTC, merged