Create new getter `VideoPlayerValue.aspectRatioOrNull`
flutter/packages pull request #3309
Opened 2023-02-27 14:28 UTC by liumcse

Currently, to get the aspect of ratio, we use `videoPlayerValue.aspectRatio`. However, after the video source is initialized, and before the actual aspect ratio is fetched, there's a brief moment when the aspect ratio is unavailable. `videoPlayerValue.aspectRatio` returns `1.0` in that case, which is not accurate, because that may not be the true aspect ratio of the video.

Using the current API of getting the aspect ratio, we have no way of telling whether the aspect ratio is unavailable, or the aspect ratio is actually `1.0`.

Ideally, I believe the value returned should be `null` if the aspect ratio is unavailable. To not break existing usage, in this PR I'm adding a new API named `aspectRatioOrNull` for this purpose.

*List which issues are fixed by this PR. You must list at least one issue.*
- API returns an inaccurate aspect ratio for a brief moment before the true aspect ratio is fetched, and developers have no way to tell.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
This is not a breaking change.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-03-01 02:37 UTC, tarrinneal requested changes
Good pr overall, make sure you update the changelog and pubspec files as well.

2023-03-01 03:12 UTC, stuartmorgan commented
You've checked off a number of checklist items that you have not actually done. I'm marking this as a draft; please mark it as ready for review when you've actually completed the checklist.

2023-03-04 18:20 UTC, stuartmorgan requested changes
(Updating review state per comment above.)

2023-03-11 15:08 UTC, stuartmorgan commented
> `videoPlayerValue.aspectRatio` returns `1.0` in that case, which is not accurate

It's the explicitly documented behavior of the method, so "not accurate" seems arguable here.

> Using the current API of getting the aspect ratio, we have no way of telling whether the aspect ratio is unavailable, or the aspect ratio is actually `1.0`.

I'm confused by this assertion. As the docs for `aspectRatio` say:

```
/// Will return `1.0` if:
/// * [isInitialized] is `false`
```

There's a clearly documented way to tell if it's unavailable. Are you saying that doesn't work? (If that is the issue, then this PR won't help, because it's using `isInitialized` to decide when to return `null`.)

2023-03-11 19:01 UTC, liumcse commented
`aspectRatio` may return 1.0 even when `initialized =`rue`.

In practice, we found that after `isInitialized` became true, video aspect ratio may still not be available for a brief moment because of `size.width` or `size.height` have not been updated to the accurate values (in fact, they may even be negative for a second).

I guess the API author of `aspectRatio` realized that problem, hence the `if (aspectRatio <= 0)` check even after knowing `isInitialized` has been set to `true`.

2023-03-11 20:43 UTC, stuartmorgan commented
> The root problem here is probably that `isInitialized` should not have been `true` before video sizings have been updated to accurate ones.

If there's a bug in the current API's behavior, the solution would be to fix that bug, rather than add new API variants.

Have you filled an issue with steps to reproduce the problem?

2023-03-15 11:28 UTC, BraveEvidence commented
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA

2023-04-04 19:49 UTC, stuartmorgan commented
Marking as a draft for now since without answers to the questions above we don't have enough information to proceed with a review; please feel free to mark as ready for review once you've filed the issue with more details.

2023-05-02 19:44 UTC, stuartmorgan commented
Since this is marked as a draft and hasn't been updated in several months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

2023-05-02 19:44 UTC, closed without merging