[Espresso] Create integration test and remove exemption
flutter/packages pull request #3367
Opened 2023-03-03 18:39 UTC by reidbaker

[#12142](https://github.com/flutter/flutter/issues/121423) 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

2023-03-04 18:25 UTC, stuartmorgan requested changes
Doh, it's been so long since I've done one of these setups that I led you astray; we forgot a critical step. The command I had you run to run it locally isn't what we use in CI on Android, because we use FTL to test Android. (I'm hoping we can get Android simulators up and running soon, in which case that command will be used for Android too.)

To enable it for FTL, you have to do the extra steps listed at https://github.com/flutter/flutter/tree/main/packages/integration_test#android-device-testing

2023-03-06 19:38 UTC, reidbaker commented
> 

There was already a file with the existing name so I added the word Integration to the file name.

2023-03-09 20:48 UTC, reidbaker commented
Hmm tests are failing with 
```
/tmp/cirrus-ci-build/packages/espresso/example/android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java:17: error: package androidx.multidex does not exist
import androidx.multidex.MultiDex;
                        ^
/tmp/cirrus-ci-build/packages/espresso/example/android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java:25: error: cannot find symbol
    MultiDex.install(this);
    ^
  symbol:   variable MultiDex
  location: class FlutterMultiDexApplication
2 errors

FAILURE: Build failed with an exception.
```

But this pr does not doe anything wtih multidex. I need to investigate but any suggestions are welcome.

2023-03-13 21:06 UTC, reidbaker commented
New test is passing locally with (from root)`dart run ./script/tool/bin/flutter_plugin_tools.dart drive-examples --android --packages espresso` 
from packages/expresso/example/android `./gradlew app:assembleAndroidTest -Pverbose=true`
But is still failing in ci. 

Any ideas are welcome. 

As an aside if you get "INSTALL_FAILED_VERIFICATION_FAILURE" then you can bypass it with `adb shell settings put global verifier_verify_adb_installs 0`

2023-03-13 21:13 UTC, reidbaker commented
I can reproduce the new failure by running `./gradlew app:mergeDexDebug` from packages/espresso/example/android

2023-03-14 15:14 UTC, reidbaker commented
https://firebase.corp.google.com/u/0/project/flutter-cirrus/testlab/histories/bh.61e29d9ae01b62d4/matrices/7984669307152441086/executions/bs.cbe8c5c67d29ab9c/videos

Test is timing out and I cant figure out why.

2023-03-14 17:19 UTC, reidbaker commented
Current plan is to debug by getting gcloud installed and trying to run `gcloud firebase test android run --type instrumentation --app build/app/outputs/apk/debug/app-debug.apk --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk --timeout 7m --results-bucket=gs://flutter_cirrus_testlab --results-dir=plugins_android_test/espresso/5839641094389760/d8d95d2c-8a7f-443d-886d-9b9aae3a2670/example/0/ --device model=redfin,version=30 --device model=starqlteue,version=26"` or some variation of that command. 


Install instructions https://cloud.google.com/sdk/docs/install-sdk#mac

2023-03-14 18:10 UTC, reidbaker commented
Unable to use gcloud to trigger builds normal google accounts are not authorized to run/modify/create projects or use existing ones. 
From flutter infra the suggestion is to use led. 
https://g3doc.corp.google.com/company/teams/flutter/infrastructure/playbook.md?cl=head#testing-repo-changes-with-led 
https://chromium.googlesource.com/chromium/src/+/HEAD/docs/infra/using_led.md
Installed as part of depot_tools.

2023-03-14 20:11 UTC, reidbaker commented
Running tests with `flutter drive --driver test_driver/integration_test.dart --target integration_test/espresso_launch_test.dart` and `lutter test integration_test/espresso_launch_test.dart` pass locally.

2023-03-14 20:45 UTC, reidbaker commented
I have been able to show that if I modify expresso_launch_test to have `expect(false, isTrue);` we still get stuck waiting for the test to timeout leading me to believe that our dart code is not getting run when we use the gradle command from https://github.com/flutter/packages/pull/3367#issuecomment-1468785378 but is being run when we execute `flutter test integration_test/espresso_launch_test.dart`

2023-03-14 20:50 UTC, reidbaker commented
It seems like I am getting the same behavior as these people but non of those solutions seem to work for me https://stackoverflow.com/questions/65412897/new-integration-test-package-just-shows-test-starting-android

2023-03-14 20:51 UTC, reidbaker commented
Also similar to this issue https://github.com/flutter/flutter/issues/86173

2023-03-14 21:16 UTC, reidbaker commented
@goderbauer Do you have any suggestions for what else I can try? 

Specifically I am trying to understand why locally from packages/expresso/example`flutter test integration_test/espresso_launch_test.dart` passes but from packages/expressso/example/android `./gradlew app:connectedAndroidTest -Ptarget=`pwd`/../integration_test/espresso_launch_test.dart` hangs on the "Test Starting" screen.

2023-03-15 14:07 UTC, stuartmorgan commented
It may be useful to compare with a PR like https://github.com/flutter/plugins/pull/4200 that set up initial integration tests for some of our other plugins. It's getting to be a while ago so it's possible that some things have changed, but it's likely still pretty close.

@bparrishMines may also have advice here since he set up a lot of the missing harnesses when we did our push on filling in testing holes.

2023-03-15 17:05 UTC, reidbaker commented
> It may be useful to compare with a PR like [flutter/plugins#4200](https://github.com/flutter/plugins/pull/4200) that set up initial integration tests for some of our other plugins. It's getting to be a while ago so it's possible that some things have changed, but it's likely still pretty close.
> 
> @bparrishMines may also have advice here since he set up a lot of the missing harnesses when we did our push on filling in testing holes.

One big thing I notice is that espresso does not actually have any dart code outside of the example directory. This means that unlike in the linked pr we cant verify the existence of a plugin. 

It is possible that the test is hanging because an integration test that launches from dart is actually not the right way to integration test this package?

2023-03-15 18:10 UTC, stuartmorgan commented
> This means that unlike in the linked pr we cant verify the existence of a plugin.

That's fine, it can be entirely a no-op.

> It is possible that the test is hanging because an integration test that launches from dart is actually not the right way to integration test this package?

It's definitely not the right way to actually *test* the package, but that's fine; the goal here is just to ensure in CI that the example launches.

2023-03-16 00:15 UTC, bparrishMines commented
This doc is a little old, but may be helpful: https://docs.google.com/document/d/1OKqAJ5rG_HPafO_E83-INtnwAKhoBuklyuJG_vauXHs/edit?usp=sharing

2023-03-16 14:37 UTC, reidbaker commented
it appears I am being stuck on this line. https://github.com/flutter/flutter/blob/007ed2a2d8fb02ac483bd02517752938d0bf51ec/packages/integration_test/android/src/main/java/dev/flutter/plugins/integration_test/FlutterTestRunner.java#L71

2023-03-16 15:26 UTC, reidbaker commented
For postarity the warning code we see is generated here https://github.com/flutter/flutter/blob/09cc1c4cdabb69f7163632afba7e0298881fbc0b/packages/integration_test/lib/integration_test.dart#L66

2023-03-16 15:27 UTC, reidbaker commented
It is likley that when I find my issue I should update the documentation here https://docs.flutter.dev/testing/integration-tests#testing-on-firebase-test-lab

2023-03-16 17:31 UTC, reidbaker commented
`gcloud firebase test android run --type instrumentation --app build/app/outputs/flutter-apk/app-release.apk --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk --timeout 7m --device model=starqlteue,version=26 --project flutter-cirrus --results-bucket=gs://flutter_cirrus_testlab`
will try to start the test after requesting access via go/flutter-firebase-on-demand-request and getting a member of flutter-infra to approve.

This command fails locally but i think it is because i am uploading the wrong artifacts.

2023-03-16 17:38 UTC, reidbaker commented
`gcloud firebase test android run --type instrumentation --app build/app/outputs/flutter-apk/app-debug.apk --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk --timeout 7m --device model=starqlteue,version=26 --project flutter-cirrus --results-bucket=gs://flutter_cirrus_testlab`
Command started a test successfully. 
https://firebase.corp.google.com/u/0/project/flutter-cirrus/testlab/histories/bh.61e29d9ae01b62d4/matrices/5019499127722619788

2023-03-16 18:26 UTC, reidbaker commented
Current theory is that if I follow https://github.com/flutter/flutter/wiki/Plugin-Tests#enabling-android-ui-tests in addition to the super call being made that this should pass.

2023-03-16 19:29 UTC, reidbaker commented
Existing tests fail in ci. 
https://firebase.corp.google.com/u/0/project/flutter-cirrus/testlab/histories/bh.61e29d9ae01b62d4/matrices/8681745030105464066/executions/bs.a49a6e43bb7bbcf0/test-cases

2023-03-17 18:43 UTC, reidbaker commented
To locally reproduce local failures run `dart run ./script/tool/bin/flutter_plugin_tools.dart native-test --android --packages espresso` from the root directory packages.

2023-03-17 18:53 UTC, reidbaker commented
Checking out main and running `dart run ./script/tool/bin/flutter_plugin_tools.dart native-test --android --packages espresso`

Give the following error
```

============================================================
|| Running for packages/espresso
============================================================

Running tests for Android...
----------------------------------------
No Android unit tests found for packages/espresso/example
No Android integration tests found for packages/espresso/example
No unit tests ran. Plugins are required to have unit tests.


The following packages had errors:
  packages/espresso:
    No unit tests ran (use --exclude if this is intentional).
See above for full details.
```

I currently believe that the tests that are failing were skipped before possibly because of the exclude rule.

2023-03-17 19:14 UTC, stuartmorgan commented
Ah, the reason that fails locally but not in CI is that they are also skipped because of script/config/exclude_native_unit_android.yaml. Looking at the blame in the other repo, when I first made having no unit tests an error in our tooling I excluded `espresso` under the (apparently mistaken) belief that it didn't need unit tests.

So perhaps those unit tests never actually worked in CI at all. Certainly not for the last several years.

2023-03-17 19:28 UTC, reidbaker commented
Further Evidence that the test does not run on main

From an unrelated curris build 
https://cirrus-ci.com/task/6359593459122176
Expresso unit tests do not appear they way they do in my failing builds. 
```
------------------------------------------------------------
  camera_android - 
ran
Ran for 1 package(s)
No issues found!
```

2023-03-17 19:52 UTC, gmackall approved these changes
LGTM! Glad to see the issue of old tests breaking had a simple answer.

2023-03-17 21:04 UTC, stuartmorgan commented
> Further Evidence that the test does not run on main
> 
> From an unrelated curris build https://cirrus-ci.com/task/6359593459122176 shard 0 (just like my builds) Expresso unit tests do not appear they way they do in my failing builds.
> 
> ```
> ------------------------------------------------------------
>   camera_android - 
> ran
> Ran for 1 package(s)
> No issues found!
> ```

That's actually a build from a PR that only affected `camera_android`. [This](https://cirrus-ci.com/task/5795364645634048) is what the excluded test looks like.

This repo is pretty aggressive about skipping packages that can't be affected by the PR. The summary at the end includes skipped and excluded tests for auditability, so if a package isn't listed on the summary it wasn't even considered due to the change detection.

(This PR runs everything because you are changing script/config, which could affect anything.)

2023-03-17 21:27 UTC, stuartmorgan commented
> Ah, the reason that fails locally but not in CI is that they are also excluded because of script/config/exclude_native_unit_android.yaml. Looking at the blame in the other repo, when I first made having no unit tests an error in our tooling I excluded `espresso` under the (apparently mistaken) belief that it didn't need unit tests.
> 
> So perhaps those unit tests never actually worked in CI at all. Certainly not for the last several years.

Sorry, I hadn't read the diff carefully enough; this comment of mine is completely wrong. The tests that don't work are `androidTest` tests, so are unrelated to the exclusion. They are native integration tests. (The native **unit** test exclusion is intentional.)

So the fact that they weren't running is a mistake. Since plugins often don't need native integration tests, they don't require exclusions the way the standard test types do.

2023-03-17 21:28 UTC, stuartmorgan approved these changes

2023-03-17 21:28 UTC, stuartmorgan commented on packages/espresso/CHANGELOG.md
> +## NEXT
This can be removed; tests are dev-only, so are exempt. You just need to add the label to override changelog detection.

2023-03-17 21:28 UTC, stuartmorgan commented on packages/espresso/example/android/app/src/androidTest/java/com/example/MainActivityTest.java
> -        onFlutterWidget(withTooltip("Increment")).perform(click(), click()).perform(click());
Could you file an issue referencing this deleted code so we don't lose track of the existence of this native integration test? We should figure it why they are broken and fix them (just not in this PR).

2023-03-20 15:59 UTC, merged