[image_picker_android] Adjust file extension in FileUtils when it does not match its mime type
flutter/packages pull request #3409
Opened 2023-03-07 23:53 UTC by SynSzakala

Sometimes a file name returned by the `ContentResolver` can have an extension that doesn't match its real type (e.g. if the file was re-encoded). 
Previously file extension was selected only based on the mime type. flutter/plugins#6096 changed it, so that the name returned by `ContentResolver` was used if available, with mime-based extension used only as fallback.
This PR fixes the regression by changing extension of the name returned from `ContentResolver` so that it matches its mime type (if known).

Fixes flutter/flutter#121878.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-03-08 00:46 UTC, stuartmorgan requested changes
Thanks for the follow up PR!

> - [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
> - [x] I updated CHANGELOG.md to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).

These changes aren't in the PR that was uploaded.

2023-03-08 00:46 UTC, stuartmorgan commented on packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
> +    return fileName.split("\\.")[0];
The basename is everything before the last `.`, not the first, so this will return the wrong name in some cases.

2023-03-08 00:46 UTC, stuartmorgan commented on packages/image_picker/image_picker_android/android/src/test/java/io/flutter/plugins/imagepicker/FileUtilTest.java
> +
Please add another test for the case where a file's basename contains `.`s.

2023-03-14 17:41 UTC, stuartmorgan approved these changes
LGTM!

2023-03-16 17:27 UTC, gmackall approved these changes
LGTM as well!

2023-03-17 08:56 UTC, SynSzakala commented
@stuartmorgan Fixed conflicts, auto-submit can be re-added.

2023-03-17 19:17 UTC, stuartmorgan commented
Thanks!

2023-03-17 19:37 UTC, merged

2023-03-20 01:04 UTC, reimager commented
Thank you all!