[video_player] Remove added listener before unmounting widget in example
flutter/packages pull request #3488
Opened 2023-03-19 14:02 UTC by gadishimwe

Fixes #122690 by removing added listener before unmounting the widget in the example code. I slightly changed the solution I proposed in the issue. I moved the code to remove the listener from `dispose` method to the listener itself because the first fix wasn't working in this example. The listener was being called one more time after calling `Navigator.pop(context)` but before the `videoPlayerController.removeListener(listener);` is called in dispose method.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-04-04 19:55 UTC, stuartmorgan requested changes
Thanks for the contribution! This will need a version update per our contributing docs (the currently unchecked items in the PR template checklist).

2023-04-04 19:55 UTC, stuartmorgan commented on packages/video_player/video_player/example/lib/main.dart
> +  void listener() {
Please give this a clearer name (e.g., `_onVideoControllerValueUpdated`).

2023-04-04 19:57 UTC, stuartmorgan commented
It would also be good to add a test of this issue; we don't currently have tests for the example, but this issue illustrates that it would benefit from tests.

2023-04-05 12:24 UTC, gadishimwe commented
> Thanks for the contribution! This will need a version update per our contributing docs (the currently unchecked items in the PR template checklist).
> > Please give this a clearer name (e.g., _onVideoControllerValueUpdated).

Hey @stuartmorgan, I just pushed a commit that applies the feedback. Thanks

2023-04-05 12:28 UTC, gadishimwe commented
> It would also be good to add a test of this issue; we don't currently have tests for the example, but this issue illustrates that it would benefit from tests.

That's true, but I don't know how I can test that. And I'm afraid I don't have enough time to look into it now. If anyone else can add a commit for it, that would be great.

2023-04-11 19:55 UTC, stuartmorgan commented
> That's true, but I don't know how I can test that.

If the issue is that a certain set of steps in the UI crashes, then it would be tested with an integration test (or a widget test if it reproduces there) that does those steps.

2023-06-20 19:54 UTC, stuartmorgan commented
Since this is marked as a draft and hasn't been updated in several months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

2023-07-06 18:44 UTC, closed without merging