[flutter_markdown] Unable to use MarkdownElementBuilder to act on no-block tag
flutter/packages pull request #3952
Opened 2023-05-10 08:48 UTC by MeandNi

fix https://github.com/flutter/flutter/issues/126402

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [  ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [  ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [  ] I updated/added relevant documentation (doc comments with `///`).
- [  ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [  ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-05-10 09:39 UTC, MeandNi commented
> Please add tests that exercise the error condition that this PR fixes↳

done

2023-05-10 10:29 UTC, domesticmouse commented
Looking at CI, looks like there are some issues:

```

Running command: "dart analyze --fatal-infos" in /tmp/cirrus-ci-build/packages/flutter_markdown
Analyzing flutter_markdown...
   info - lib/src/builder.dart:457:15 - Use 'isEmpty' instead of 'length' to test whether the collection is empty. Try rewriting the expression to use 'isEmpty'. - prefer_is_empty
   info - test/custom_syntax_test.dart:136:31 - Unnecessary use of double quotes. Try using single quotes unless the string contains single quotes. - prefer_single_quotes
   info - test/custom_syntax_test.dart:256:17 - Unnecessary use of double quotes. Try using single quotes unless the string contains single quotes. - prefer_single_quotes
3 issues found.
```

2023-05-10 21:42 UTC, domesticmouse commented
Cool! Can you now please update the version and add some notes to the changedoc about this change? It won't be released to the world without bumping the version =)

2023-05-11 04:11 UTC, domesticmouse approved these changes
PTAL @stuartmorgan

2023-05-11 14:13 UTC, stuartmorgan requested changes

2023-05-11 14:13 UTC, stuartmorgan commented on packages/flutter_markdown/CHANGELOG.md
> +* Support custom rendering of those tags without children.
Please follow the style in [the guide linked from the PR checklist above](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style)

2023-05-11 14:13 UTC, stuartmorgan commented on packages/flutter_markdown/CHANGELOG.md
> +* Support custom rendering of those tags without children.
Remove "those"

2023-05-11 14:13 UTC, stuartmorgan commented on packages/flutter_markdown/test/custom_syntax_test.dart
> +    'Custom rendering of those tags without children',
Remove "those"

2023-05-30 20:36 UTC, stuartmorgan approved these changes
LGTM

2023-05-30 20:51 UTC, merged