[url_launcher] Importing BuildConfig to UrlLauncher.java
flutter/packages pull request #4249
Opened 2023-06-19 16:04 UTC by ChopinDavid

This is a very simple PR. Simply adding an import for `BuildConfig` to url_launcher.java. This would allow our team to build with AGP 8.x.

Fixes [flutter-#128204]((https://github.com/flutter/flutter/issues/128204))

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-06-22 19:08 UTC, Hixie commented
@stuartmorgan Is it worth adding a test with that version of AGP?

2023-06-22 19:11 UTC, stuartmorgan commented
> @stuartmorgan Is it worth adding a test with that version of AGP?

We can't yet; it requires a version of Java that we don't have in CI. The plan is to look into rolling all our examples forward to 8 once we migrate Android tests to LUCI, since it should hopefully be easier to manage our Java version at that point.

2023-06-22 21:29 UTC, ChopinDavid commented
If there is a means to specifying AGP version in a test (I'm unsure how as of now), I suppose we wait until gradle 8 is available in CI, we write the test, then revisit this PR?

2023-06-22 22:28 UTC, stuartmorgan commented
So far our approach to AGP 8 has been to fix issues, with the understanding that we will automatically pick up testing for all of it as we roll our CI and example deps forward.

2023-06-23 10:12 UTC, ChopinDavid commented
@stuartmorgan So, a test exemption is in order then?

2023-06-23 14:43 UTC, stuartmorgan commented
Yes, a test exemption would be consistent with our handling of AGP-8-specific issues so far.

2023-06-27 00:12 UTC, gmackall requested changes
Thanks for the contribution!

As is I don't believe this fixes the issue, but I left more detail in a comment on the approach I think we should take. Let me know if you disagree, I'm happy to discuss

2023-06-27 00:12 UTC, gmackall commented on packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncher.java
> +import io.flutter.plugins.urllauncher.BuildConfig;
I don't believe this line allows for building with AGP 8.x - I tried adding this change to `url_launcher_android`, and modifying the example app to use AGP and gradle 8.0.2, and I still got the same error regarding `BuildConfig`.

I think what we need to do here is what is described in the original issue, which is adding 
```
buildFeatures {
    buildConfig true
  }
```
to the `android{}` section of `url_launcher_android/android/build.gradle`.

2023-07-13 18:56 UTC, reidbaker commented
@ChopinDavid is this still on your radar? If not that is totally understandable we can close this to get it off our queue.

2023-07-20 18:56 UTC, ChopinDavid commented
@reidbaker definitely off of my radar, I think my team no longer needs this fix. And there seems to be some questions around whether or not this would actually fix the issue mentioned anyways?

2023-07-20 23:01 UTC, Hixie commented
Follow-up in https://github.com/flutter/packages/pull/4535.

2023-07-20 23:01 UTC, closed without merging