[pigeon] Recursively create output target files
flutter/packages pull request #4458
Opened 2023-07-13 15:57 UTC by Nitin-Poojary

Recursively creates output target files before trying to write to it.

closes #[128820](https://github.com/flutter/flutter/issues/128820)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-07-13 22:45 UTC, tarrinneal commented
@stuartmorgan do you think this is something that can be reasonably tested?

2023-07-14 11:45 UTC, stuartmorgan commented
I don't see why not; we have lots of tests that generate output files. All we need is one that does so with a target directory that doesn't exist.

2023-07-14 21:06 UTC, tarrinneal commented
> I'm sorry, but I didn't quite understand your point. Could you please clarify what I need to do?

Can you add a test in the pigeon_lib_test.dart file that tests writing a file in a directory that doesn't exist?

2023-07-18 08:13 UTC, Nitin-Poojary commented
I apologize, but I am having difficulty understanding the approach required to write this test. Could you please provide guidance or instructions on how to proceed?

2023-07-20 13:37 UTC, Nitin-Poojary commented
> I apologize, but I am having difficulty understanding the approach required to write this test. Could you please provide guidance or instructions on how to proceed?

@stuartmorgan

2023-07-20 17:30 UTC, stuartmorgan requested changes
> I apologize, but I am having difficulty understanding the approach required to write this test. Could you please provide guidance or instructions on how to proceed?

To test as a unit test, you would create a temp directory (see the logic in `withTempFile` for an example) and then call `shouldGenerate` on a generator with options that would write to a non-existent subdirectory of that temp directory, then check that it was created.

Alternately it could be done as an end-to-end test [here](https://github.com/flutter/packages/blob/442d9db34717454e99cd27b188724b858d72227e/packages/pigeon/tool/shared/test_suites.dart#L405) by using an output path that doesn't exist.

2023-07-21 16:43 UTC, Nitin-Poojary commented on packages/pigeon/tool/shared/test_suites.dart
>    ];
Like this?

2023-08-07 17:06 UTC, stuartmorgan commented on packages/pigeon/tool/shared/test_suites.dart
> +    // Test writing a file in a directory that doesn't exist
Nit: missing final period.

2023-08-07 17:35 UTC, Nitin-Poojary commented on packages/pigeon/lib/pigeon_lib.dart
> +      dartOutPath: options.dartOut,
I made this change to investigate something, but then I forgot to revert it. Later, I mistakenly assumed that I had made the change intentionally, and I apologize for that.

2023-08-08 00:01 UTC, tarrinneal approved these changes
Thanks for putting this together!

2023-08-08 00:38 UTC, merged

2023-08-08 06:35 UTC, Nitin-Poojary commented
@tarrinneal @stuartmorgan I wanted to say a big thank you for your support and guidance during the review and merging of my pull request. Your help has been invaluable, and I'm grateful for the opportunity to contribute to this project.

2023-08-08 22:27 UTC, tarrinneal commented
> @tarrinneal @stuartmorgan I wanted to say a big thank you for your support and guidance during the review and merging of my pull request. Your help has been invaluable, and I'm grateful for the opportunity to contribute to this project.

We're always happy to help community members land good pr's! Thank you for putting in the effort and time to get this through to the finish line!