[webview_flutter] Adds app facing implementation to override console log
flutter/packages pull request #4705
Opened 2023-08-15 07:58 UTC by mvanbeusekom

Adds the app facing implementation for registering a JavaScript console callback. This will allow developers to receive JavaScript console messages in a Dart callback.

This PR contains the `webview_flutter` specific changes from PR #4541.

Related issue: flutter/flutter#32908

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-09-30 09:45 UTC, mvanbeusekom commented
HI @stuartmorgan, @bparrishMines,

This is the last PR updating the app facing package with support for registering a callback to catch the JavaScript console messages. Would appreciate a review.

2023-10-01 00:00 UTC, stuartmorgan requested changes

2023-10-01 00:00 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter/pubspec.yaml
We should bump the `_android` and `_wkwebveiw` constraints to pick up the implementations, so that the feature being added here will work even if someone doesn't `flutter pub upgrade`.

2023-10-01 07:12 UTC, mvanbeusekom commented on packages/webview_flutter/webview_flutter/CHANGELOG.md
> +>>>>>>> upstream/main
Missed that, thank you for pointing that out.

2023-10-01 07:12 UTC, mvanbeusekom commented on packages/webview_flutter/webview_flutter/lib/src/webview_controller.dart
> +  /// WebKit framework unfortunately doesn't provide a build in method to
Fixed.

2023-10-01 07:12 UTC, mvanbeusekom commented on packages/webview_flutter/webview_flutter/pubspec.yaml
Fixed.

2023-10-01 12:05 UTC, stuartmorgan approved these changes
Thanks, LGTM!

2023-10-01 12:06 UTC, merged