[video_player] Adds option `isLooping` and `volume` to VideoPlayerController constructor
flutter/packages pull request #4913
Opened 2023-09-13 07:00 UTC by vanvixi

Adds option `isLooping` and `volume` to VideoPlayerController constructor

Can be used as follows:
```
final VideoPlayerController controller = VideoPlayerController.networkUrl(
  Uri(),
  isLooping: true,
  volume: 0,
);
```

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-09-13 10:06 UTC, tarrinneal requested changes
You've checked all the boxes on the pr checklist, but haven't done all of the items listed in them. Please try to be more thorough when reading through the checklist in the future.

This will need at least some adjustments to existing tests, if not new tests for this change. 

It seems to me that when this was designed the parameters may have been kept sparse for a reason. Perhaps @stuartmorgan has some insight into this.

2023-09-13 11:29 UTC, stuartmorgan commented
> [x] I listed at least one issue that this PR fixes in the description above.

What problem is this PR solving? Please file an issue using the "Feature request" template and filling in the requested information, so that it's clear what the goal of this proposal is.

2023-09-16 12:43 UTC, stuartmorgan requested changes
(Updating review flag to reflect my comment above.)

2023-09-16 15:17 UTC, vanvixi commented on packages/video_player/video_player/lib/video_player.dart
> +    double volume = 1.0,
@tarrinneal 
Thank you for your reminder.
I fixed it. I renamed `isLooping` -> `loop`.
Also I added the option: `playAfterInitialized`. What do you think about this option?

2023-09-16 15:18 UTC, vanvixi commented
> What problem is this PR solving? Please file an issue using the "Feature request" template and filling in the requested information, so that it's clear what the goal of this proposal is..

@stuartmorgan 
Iam currently developing a video playback application similar to TikTok. During the development process, I need to prepare the next video and configure necessary options such as "loop, volume, playAfterInitialized" in advance. The changes in this pull request (PR) make my application faster, and I believe those who are working on a video application like TikTok will also need these options in the constructor.

2023-09-16 20:24 UTC, stuartmorgan commented
@vanvixi Again, please [file an issue](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=3_feature_request.yml). As [explained in our docs](https://github.com/flutter/flutter/wiki/Tree-hygiene#overview) an issue is the place for discussion of whether a feature should exist, not a PR.

> The changes in this pull request (PR) make my application faster

Specific details on this sound like good information to include in the issue.

2023-09-17 06:33 UTC, vanvixi commented
@stuartmorgan 
I have added an issues here: https://github.com/flutter/flutter/issues/134894

2023-10-09 12:19 UTC, stuartmorgan commented
Closing, as we never received a response on the issue about the reason for this change.

2023-10-09 12:19 UTC, closed without merging