[url_launcher_android] Enable Android WebView to open PDFs and non-HTTP URLs (mailto:, tel:, sms:, etc.)
flutter/packages pull request #5017
Opened 2023-09-27 19:36 UTC by michaelmiles1

This PR adds the ability of the launched WebView in Android to follow and open non-HTTP links by starting new Intents, such as opening a PDF viewer or your preferred email application.

Issues fixed:
https://github.com/flutter/flutter/issues/106331 - this fix was inspired by the attempted fix https://github.com/flutter/plugins/pull/6006, but I had to extend the WebViewClient to make it testable
https://github.com/flutter/flutter/issues/27309 - opening PDFs wasn't causing a crash for me, but was not opening PDFs on any Android device

Had issues with the last PR because of the CLA. Here's the last PR: https://github.com/flutter/packages/pull/4477

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

2023-09-27 19:39 UTC, michaelmiles1 commented on packages/url_launcher/url_launcher_android/example/lib/main.dart
> +                ),
The test page now launches any URL the user inputs

2023-09-27 19:43 UTC, michaelmiles1 commented on packages/url_launcher/url_launcher_android/android/src/test/java/io/flutter/plugins/urllauncher/WebViewActivityTest.java
> +  }
Unit tests to make sure that the URL launcher parses the URL properly based on scenario (.pdf, :mailto, etc)

2023-09-27 20:40 UTC, michaelmiles1 commented
Will look in to and fix build issues tomorrow 👍

2023-10-09 16:37 UTC, gmackall commented
Sorry for the delay on reviewing, I was traveling for the last week. I'll make sure to get this reviewed either today or tomorrow!

2023-10-10 21:27 UTC, gmackall requested changes
Mostly LGTM, just a couple of comments!

2023-10-10 21:27 UTC, gmackall commented on packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/FlutterWebViewClient.java
> +    if (!url.startsWith("http://") && !url.startsWith("https://")) {
Can you change these checks, and the one above for `.pdf` to be non case sensitive?

2023-10-16 17:17 UTC, stuartmorgan commented
@gmackall Are you okay with unilaterally enabling users to leave the app even when the plugin client has requested the in-app webview mode? This seems like something that clients might want to be able to control, either with an opt-in or an opt-out.

2023-10-16 19:10 UTC, michaelmiles1 commented
Resolved issues, thanks!

2023-10-17 17:03 UTC, gmackall commented
> @gmackall Are you okay with unilaterally enabling users to leave the app even when the plugin client has requested the in-app webview mode? This seems like something that clients might want to be able to control, either with an opt-in or an opt-out.

I hadn't considered that, but I agree it does seem likely clients would want control over that. Have the other platform implementations solved into a similar problem?

2023-10-17 17:08 UTC, stuartmorgan commented
> Have the other platform implementations solved into a similar problem?

So far only iOS supports a somewhat similar mode, and it's more akin to Android Custom Tabs where we don't have much control over how things work. We could make this a flag in [`WebViewConfiguration`](https://github.com/flutter/packages/blob/main/packages/url_launcher/url_launcher/lib/src/types.dart#L27-L54)

2023-10-17 17:15 UTC, stuartmorgan commented
(The other option is that we could land this as-is, and then add configuration only if people request it. In general, we don't want to support every possible configuration option otherwise `url_launcher` will be as complicated as `webview_flutter`; this is just potentially a special case since it used to be restricted and now won't be.)

2023-10-18 17:49 UTC, gmackall commented
> (The other option is that we could land this as-is, and then add configuration only if people request it. In general, we don't want to support every possible configuration option otherwise `url_launcher` will be as complicated as `webview_flutter`; this is just potentially a special case since it used to be restricted and now won't be.)

I'm okay with landing this as is and gauging feedback. Do you want to do secondary review as the overall url_launcher codeowner?

2023-10-18 17:55 UTC, gmackall approved these changes

2023-10-18 17:55 UTC, gmackall commented on packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/FlutterWebViewClient.java
> +   * This method is deprecated in API 24. Still overridden to support
nit: 
```suggestion
   * This method is deprecated in API 24. It is still overridden to support
```

2023-10-18 17:55 UTC, gmackall commented on packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/FlutterWebViewClient.java
> +    // Check if URL is not an HTTP(S) request
nit: end with period

2023-10-18 17:55 UTC, gmackall commented on packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/FlutterWebViewClient.java
> +    // Otherwise, let WebView load URL
nit: end with period

2023-10-19 19:28 UTC, michaelmiles1 commented
[ ] upperCase and lowerCase methods must pass in locale (lint)

2023-10-25 12:14 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/FlutterWebViewClient.java
> +      } else {
`else` isn't necessary after an early return.

2023-10-25 12:14 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/FlutterWebViewClient.java
> +      } else {
Same.

2023-10-25 12:16 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/FlutterWebViewClient.java
> +    if (url.toLowerCase(Locale.US).endsWith(".pdf")) {
Why is this using the URL string rather than a content type? A PDF URL doesn't need to end in `pdf`.

2023-12-12 20:49 UTC, stuartmorgan commented
Are you still planning on updating this PR to address the review comments above?

2024-01-11 19:55 UTC, gmackall commented
Thanks for your contribution! Since I haven't seen a reply, I'm going to reluctantly close this pull request for now (to get it off our review queue), but if you get time to address the comments, please feel free to re-open this PR!

2024-01-11 19:55 UTC, closed without merging