Expose the allowsLinkPreview property in WKWebView for iOS
flutter/packages pull request #5029
Opened 2023-09-28 17:15 UTC by camfrandsen

Based off of https://github.com/flutter/plugins/pull/5110 So most of the credit goes to @b099l3
Also exposed it through the webview_controller

This PR fixes this issue:
- https://github.com/flutter/flutter/issues/69748
- (duplicate) https://github.com/flutter/flutter/issues/100783

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

2023-09-28 17:25 UTC, camfrandsen commented
@cyanglaz @bparrishMines I saw that you reviewed https://github.com/flutter/plugins/pull/5110 the first time. Sorry to make you re-review it... but I would love if you could review this. I did my best to port it over from that pr. Thank you for your help with this!
Note, I checked the Linux and Mac checks, and saw that they had failed on previous pulls that went in, so I am assuming they failing on the main branch? Let me know though if there is something I need to do
@b099l3 I figured you would want to be aware that I have ported your patch over to the new repo

2023-10-23 19:29 UTC, MitchellGoodwin commented
cc @bparrishMines

2023-10-24 20:10 UTC, b099l3 commented
@camfrandsen No worries, I'm glad it was of some use. 

I had a guilt in the back of my mind to come back to it at some point and get it merged. So I can sleep easily now. 😅

2023-11-01 20:17 UTC, camfrandsen commented
I am splitting this into two pulls since I touched the webview_flutter_platform_interface:
https://github.com/flutter/packages/pull/5292
https://github.com/flutter/packages/pull/5293

2023-11-01 21:25 UTC, stuartmorgan commented
> I am splitting this into two pulls since I touched the webview_flutter_platform_interface

That's step 3 of the process, which should only be done after the previous steps (which include approvals of the combined PR) are complete.

2023-11-01 21:40 UTC, camfrandsen commented
@stuartmorgan Ah, sorry about that. I looked at the failures of the checks, and it said that it needed to be broken up... I will re-open this one and close the other two.

2023-11-07 21:14 UTC, bparrishMines reviewed
The `webview_flutter_wkwebview` portion of this is blocked by https://github.com/flutter/flutter/issues/134777.

2023-11-07 21:14 UTC, bparrishMines commented on packages/webview_flutter/webview_flutter_platform_interface/lib/src/legacy/types/web_settings.dart
> +  final bool? allowsLinkPreview;
I noticed this PR is also making changes in the `legacy/` folders in each package. We no longer support that version, so you shouldn't need to change anything in these folders.

2024-01-09 20:51 UTC, stuartmorgan commented
Update from triage: still waiting on the wrapper generator, which is currently under very active development.

2024-02-12 23:35 UTC, hellohuanlin commented
I am converting this to draft. feel free to request my review when it's ready.

2024-04-11 21:47 UTC, ftntming commented
Any updates on this?

2024-06-04 19:46 UTC, stuartmorgan commented
Update from triage: the conversion to the new wrapper automation that this is blocked on is likely to be done sometime around August.

2024-07-23 19:46 UTC, stuartmorgan commented
Update from triage: still likely on track for August.

2024-09-24 23:04 UTC, Piinks commented
(PR Triage): Hey @stuartmorgan is this still planned to move forward? Is it blocked on something?

2024-09-25 18:58 UTC, stuartmorgan commented
https://github.com/flutter/packages/pull/6602 is the blocking issue; it's just slipped slightly.

2024-10-29 19:43 UTC, stuartmorgan commented
From triage: This should be unblocked soon; https://github.com/flutter/packages/pull/7794 updates Android, and a similar PR for iOS will follow shortly.

2025-01-16 15:07 UTC, stuartmorgan commented
Sorry for the longer-than-expected delay here. https://github.com/flutter/packages/pull/8311 will unblock this, and is going through final review now.

2025-03-18 19:42 UTC, stuartmorgan commented
From triage: @camfrandsen Sorry for the long delay on the blocking PR. Are you still planning on updating this for the new API?

2025-03-31 20:19 UTC, bparrishMines commented
I went ahead and updated the code to the new `ProxyApi` wrapper. There doesn't seem to be a comparable feature on Android to control preview links.

2025-04-01 14:17 UTC, stuartmorgan-g commented
Sounds like this should be ready for review then.

2025-04-01 14:56 UTC, stuartmorgan-g requested changes

2025-04-02 18:16 UTC, bparrishMines commented on packages/webview_flutter/webview_flutter_wkwebview/lib/src/common/platform_webview.dart
> +  /// numbers.
Good suggestion. I forget that just copy/pasting the native docs doesn't always translate well to dart style.

2025-04-02 18:17 UTC, bparrishMines commented on packages/webview_flutter/webview_flutter_wkwebview/lib/src/webkit_webview_controller.dart
> +  Future<void> setAllowsLinkPreview(bool allow) {
I moved inspectable and onBackChanged as well

2025-04-17 17:14 UTC, stuartmorgan-g approved these changes
LGTM. @bparrishMines I believe you can still provide the second approval even though you've pushed changes.

2025-04-17 19:27 UTC, bparrishMines approved these changes
LGTM

2025-04-17 19:28 UTC, merged