fix: isDeviceSupported on ios
flutter/packages pull request #5125
Opened 2023-10-12 09:05 UTC by techno-disaster

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

Fixes: https://github.com/flutter/flutter/issues/116179

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-10-16 14:56 UTC, stuartmorgan requested changes
Thanks for the contribution! As discussed in Discord, this will need a native unit test.

2023-10-16 14:56 UTC, stuartmorgan commented on packages/local_auth/local_auth/CHANGELOG.md
> +* Implement isDeviceSupported for ios.
There are no changes to the `local_auth` package, so it shouldn't have a changelog or version change.

2023-10-16 14:56 UTC, stuartmorgan commented on packages/local_auth/local_auth_ios/CHANGELOG.md
> +* Implement isDeviceSupported for ios.
```suggestion
* Implements isDeviceSupported for iOS.
```

2023-10-16 14:56 UTC, stuartmorgan commented on packages/local_auth/local_auth_ios/ios/Classes/FLTLocalAuthPlugin.m
> +  LAContext *context = [[LAContext alloc] init];
This will need to use the factory, like all of the other methods, for testing.

2023-10-16 14:56 UTC, stuartmorgan commented on packages/local_auth/local_auth_ios/ios/Classes/FLTLocalAuthPlugin.m
> +  }
You can box expressions in addition to literals; this whole block is equivalent to `return @(the current if condition);`.

2023-10-16 14:56 UTC, stuartmorgan commented on packages/local_auth/local_auth_ios/ios/Classes/FLTLocalAuthPlugin.m
> +  NSError *authError = nil;
You aren't using this, so you can just eliminate it.

2024-01-02 23:46 UTC, goderbauer commented
@techno-disaster Hello from our triage meeting. Do you still have plans to address the feedback given above?

2024-01-05 04:54 UTC, techno-disaster commented
> @techno-disaster Hello from our triage meeting. Do you still have plans to address the feedback given above?

Yes, plan to get to it as soon as I find some free time, but please feel free to takeover the PR if required.

2024-02-01 19:36 UTC, stuartmorgan approved these changes
I pushed changes that addressed my comments; @jmagman do you want to do the final review?

2024-02-07 22:42 UTC, jmagman approved these changes
LGTM, thanks for the contribution!

2024-02-07 22:50 UTC, merged