[flutter_markdown] Strip leading whitespace from list items
flutter/packages pull request #5294
Opened 2023-11-02 01:33 UTC by krozett

In line with standard Markdown practice, whitespace at the beginning of list items is removed.

Fixes [Flutter issue #134847
](https://github.com/flutter/flutter/issues/134847)

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-11-02 02:10 UTC, domesticmouse reviewed
Please add a test to make sure this doesn't revert later

2023-11-03 03:38 UTC, domesticmouse approved these changes

2023-11-03 22:32 UTC, domesticmouse commented
PTAL @stuartmorgan

2023-11-06 16:20 UTC, tarrinneal approved these changes
Approval with the typo fix. Thanks for throwing this together.

2023-11-06 16:20 UTC, tarrinneal commented on packages/flutter_markdown/CHANGELOG.md
> +* Removes leading whitspace from list items.
typo: whitespace

2023-11-06 16:21 UTC, tarrinneal requested changes
typo change then approval :)

2023-11-06 18:13 UTC, krozett commented on packages/flutter_markdown/CHANGELOG.md
> +* Removes leading whitspace from list items.
Fixed!

2023-11-06 18:18 UTC, tarrinneal approved these changes

2023-11-06 19:35 UTC, merged