[in_app_purchase] add storefront in skpaymentqueuewrapper
flutter/packages pull request #5348
Opened 2023-11-07 18:46 UTC by cyanglaz

Add `Future<SKStorefrontWrapper?> storefront()` method in SKPaymentQueue wrapper

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-11-10 18:02 UTC, stuartmorgan requested changes

2023-11-10 18:02 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/InAppPurchasePlugin.m
> +  if (@available(iOS 13.0, *)) {
We should include macOS 10.15+ here too.

2023-11-10 18:02 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/InAppPurchasePlugin.m
> +    NSLog(@"storefront is not avaialbe in iOS below 13.0.");
And this should mention both iOS and macOS.

2023-11-10 18:02 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/InAppPurchasePluginTests.m
> +  if (@available(iOS 13, *)) {
Or macOS 10.15

2023-11-10 18:02 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_storekit/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
> +  /// Calls [`[SKPaymentQueue storefront]`](https://developer.apple.com/documentation/storekit/skpaymentqueue/3182430-storefront?language=objc)
Let's document that it just returns `nil` (vs throwing) on versions where it's not available.

2023-11-11 03:55 UTC, cyanglaz commented on packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/FIAPaymentQueueHandler.h
> +@property(NS_NONATOMIC_IOSONLY, readonly, nullable)
The storefront property in SKPaymentQueue is nonatomic on iOS. I tried to keep it the sam way but yeah we don't need it. Will revert to nonatomic for all.

2023-11-14 18:36 UTC, cyanglaz commented
@stuartmorgan Updated as per your comments. PTAL!

2023-11-15 12:44 UTC, stuartmorgan approved these changes
LGTM with nits.

2023-11-15 12:44 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/InAppPurchasePluginTests.m
> +    {
Nit: These should be two separate test methods, rather than sub-blocks of the same test. Unit tests should each test as few things as is feasible.

2023-11-15 12:44 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_storekit/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
> +  /// Calls [`[SKPaymentQueue storefront]`](https://developer.apple.com/documentation/storekit/skpaymentqueue/3182430-storefront?language=objc)
This is missing a period.

2023-11-15 12:44 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_storekit/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
> +  /// Returns `null` if the user's device is below iOS 13.0 or macOS 10.15.
And a blank comment line before this one, per Effective Dart.

2023-11-15 23:22 UTC, merged