Update README of `package:process`
flutter/packages pull request #5475
Opened 2023-11-24 22:35 UTC by bartekpacia

This PR fixes https://github.com/flutter/flutter/issues/136221.

BTW it's a great package! I use it extensively in [patrol_cli] and love it.

[patrol_cli]: https://pub.dev/packages/patrol_cli

2023-11-28 19:49 UTC, stuartmorgan requested changes
This requires a version change, per our contributing docs. (I would suggest not deleting the checklist from the PR description in the future, as it covers required steps like that one.)

2023-12-08 16:21 UTC, bartekpacia commented on packages/process/CHANGELOG.md
> +* Remove mention of the removed record/replay feature from README.
Sorry again, I missed it.

2023-12-13 17:31 UTC, stuartmorgan requested changes

2023-12-13 17:31 UTC, stuartmorgan commented on packages/process/CHANGELOG.md
> +* Remove mention of the removed record/replay feature from README.
This was copied instead of moved.

2023-12-13 18:03 UTC, bartekpacia commented on packages/process/CHANGELOG.md
> +* Remove mention of the removed record/replay feature from README.
🤦🏻

2023-12-13 18:07 UTC, stuartmorgan commented on packages/process/CHANGELOG.md
> +* Remove mention of the removed record/replay feature from README.
You deleted the new, corrected one (which addressed my original comment) instead of the old one.

2024-01-23 20:57 UTC, stuartmorgan commented
@bartekpacia Are you still planning on updating this per the comments above?

2024-01-24 16:25 UTC, bartekpacia commented
@stuartmorgan yes, I pushed the changes.

2024-01-25 19:37 UTC, merged