[css_colors] Adopt code excerpts in README
flutter/packages pull request #5478
Opened 2023-11-26 05:44 UTC by mike-v2

Updates the README to use a compiled excerpt source for its example of importing and using `CSSColors`.

Part of [flutter/flutter#102679](https://github.com/flutter/flutter/issues/102679) 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-11-28 09:26 UTC, tarrinneal approved these changes
lgtm with a nit. @stuartmorgan for second review.

2023-11-28 09:26 UTC, tarrinneal commented on packages/css_colors/CHANGELOG.md
> +* Updates README to improve example of using `CSSColors`.
Improves README example and updates it to use code excerpts.

2023-11-29 21:57 UTC, stuartmorgan requested changes

2023-11-29 21:57 UTC, stuartmorgan commented on packages/css_colors/example/lib/readme_excerpts.dart
It would be really easy for us to get this from an actual example main.dart rather than having to maintain a second file. I think it'll also be pretty confusing to have the `example` directory and pubspec and such, but not actually have an example to run.

Given that, I think we should either wait for https://github.com/flutter/packages/pull/5512, or fold creating an actual example into this PR.

2023-12-01 19:00 UTC, stuartmorgan commented on packages/css_colors/example/lib/readme_excerpts.dart
Alternately, we could do this with `test/`, since looking at the other PR I'm not sure we actually want an example.

2023-12-12 21:19 UTC, stuartmorgan approved these changes
LGTM with nit, thanks!

2023-12-12 21:19 UTC, stuartmorgan commented on packages/css_colors/README.md
>  Import
The entire "Import" section, including the excerpt, can be removed; the installation tab on pub.dev has that information now, so we are removing it from READMEs.

2023-12-12 21:19 UTC, stuartmorgan commented on packages/css_colors/test/css_colors_test.dart
> +// #docregion Import
And then these can be removed as well.

2023-12-13 18:12 UTC, merged