[image_picker] Remove input element after completion
flutter/packages pull request #5654
Opened 2023-12-12 17:06 UTC by Amir-P

This PR attempts to remove the input element added to the DOM after image selection is completed.

Fixes https://github.com/flutter/flutter/issues/139986

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2023-12-13 20:26 UTC, ditman requested changes
Small simplification of the fix.

2023-12-13 20:26 UTC, ditman commented on packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart
> +  void _remove(html.Element element) => _target.children.clear();
This `_remove(element)` is not removing element, it's clearing _target.children.

2023-12-13 20:26 UTC, ditman commented on packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart
> +    return _getSelectedXFiles(input).whenComplete(() => _remove(input));
```suggestion
    return _getSelectedXFiles(input).whenComplete(() => input.remove());
```

2023-12-14 19:56 UTC, Amir-P commented
Done. At first I wanted to just remove the input like you said but I saw that `_target.children.clear()` is called before injecting input element and thought you prefer that. @ditman

2023-12-21 06:39 UTC, Amir-P commented
@ditman could you review the PR please? This bug affects the usage of this plugin in our Web app.

2024-01-03 23:42 UTC, ditman commented
> This bug affects the usage of this plugin in our Web app.

How so, @Amir-P?

2024-01-03 23:50 UTC, ditman approved these changes
LGTM, thanks for cleaning this up!

2024-01-03 23:53 UTC, ditman commented
Ah, we need two reviewers for this one!

/cc @mdebbar can you PTAL? (I think you commented in the OG issue!)

2024-01-04 00:02 UTC, mdebbar approved these changes
Thanks for the fix!

2024-01-05 00:29 UTC, merged