[url_launcher] Add `InAppBrowserConfiguration` parameter in implementations
flutter/packages pull request #5759
Opened 2023-12-26 13:01 UTC by Alex-Usmanov

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2024-01-03 16:08 UTC, stuartmorgan commented
Marking as a draft for now; the sub-PRs can't proceed without the dependencies landing first. The overall pre-review is done in the main PR.

2024-01-29 13:13 UTC, stuartmorgan commented
> it seems to have slipped through the cracks.

You only marked it as ready for review at the end of last week; it often takes more than two working days for a PR to be reviewed.

2024-01-29 13:18 UTC, Alex-Usmanov commented
Sorry, did not mean to be pushy. I am just quite unaware of the process and assumed that once the child prs are going to be taken care of once the main one was approved.

Since this one was in drafts for a month, I thought this one got lost. 

Once again sorry for misunderstanding and disturbance!

2024-01-29 13:35 UTC, stuartmorgan commented
> I am just quite unaware of the process

We follow the process described at https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins

> Since this one was in drafts for a month, I thought this one got lost.

We don't generally look at draft PRs, we wait for the author of the PR to mark it as ready for review.

2024-02-01 15:53 UTC, stuartmorgan requested changes

2024-02-01 15:53 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_android/CHANGELOG.md
> +* Implements taking in `BrowserConfiguration` parameter.
"Adds support for `BrowserConfiguration`."

2024-02-01 15:53 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_android/example/pubspec.yaml
> +dependency_overrides:
This should not be needed; the platform interface should be using version constraints at this point.

2024-02-12 17:17 UTC, stuartmorgan approved these changes
LGTM, @gmackall for secondary review.

2024-02-13 06:42 UTC, gmackall approved these changes
LGTM!

2024-02-13 19:17 UTC, merged