[local_auth]: Renamed `local_auth_ios` to `local_auth_darwin`
flutter/packages pull request #5809
Opened 2024-01-05 15:06 UTC by OutdatedGuy

Renames `local_auth_ios` to `local_auth_darwin`

resolves https://github.com/flutter/flutter/issues/141020

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added newxtests to check the change I am making, or this PR is [test-exempt].
- [x] All existin  and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2024-01-05 16:18 UTC, stuartmorgan requested changes

2024-01-05 16:18 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/.gitignore
Why are there so many new files in a move?

2024-01-05 16:18 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/analysis_options.yaml
Did you run `flutter create` on this package? That should not have been necessary.

This file cannot exist in our repo, and is why a lot of the CI is failing.

2024-01-05 16:18 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
Why are all of the app icons new files instead of moves?

2024-01-05 16:18 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/example/ios/Runner.xcodeproj/project.pbxproj
Why are there so many changes in this file?

2024-01-05 16:18 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/example/ios/Runner.xcodeproj/project.pbxproj
> +		331C80F4294D02FB00263BE5 /* RunnerTests.m in Sources */ = {isa = PBXBuildFile; fileRef = 331C80F3294D02FB00263BE5 /* RunnerTests.m */; };
You've broken compilation of the unit tests; see `Mac_arm64 ios_platform_tests_shard_1 master`

2024-01-05 16:18 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/pubspec.yaml
> +description: "iOS implementation of the local_auth plugin."
Why are there so many style changes in this file?

2024-01-05 16:18 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/pubspec.yaml
> +  mockito: ^5.4.4
This violates repository policy and will not pass CI.

2024-01-09 11:59 UTC, stuartmorgan requested changes
I'll do a full re-review sometime this week, but one initial note from CI:

2024-01-09 11:59 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/pubspec.yaml
>  version: 1.1.5
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8759389953683448721/+/u/Run_package_tests/CHANGELOG_and_version_validation/stdout

2024-01-10 18:36 UTC, stuartmorgan requested changes
Mostly looks good now! Just some minor things.

2024-01-10 18:36 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/darwin/local_auth_darwin.podspec
> +  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com', 'Om Phatak' => 'everythingoutdated@gmail.com' }
This line should use the standard boilerplate; we don't list individual authors in this file.

2024-01-10 18:36 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/example/ios/RunnerTests/FLTLocalAuthPluginTests.m
This file should move to `darwin/Tests/`, and the reference in the Xcode project updated accordingly. (You'll want to change the file's reference type from group-local to project-local in the Xcode UI).

2024-01-10 18:36 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/example/pubspec.yaml
>      #   local_auth: ^x.y.z
This should be `local_auth_darwin:` (it was wrong before too, we just didn't catch it).

2024-01-10 19:11 UTC, OutdatedGuy commented on packages/local_auth/local_auth_darwin/example/ios/RunnerTests/FLTLocalAuthPluginTests.m
Hi, I don't use XCode much so I have no idea what you mean. Can someone else do this instead?

2024-01-13 19:16 UTC, OutdatedGuy commented on packages/local_auth/local_auth_darwin/example/ios/RunnerTests/FLTLocalAuthPluginTests.m
@jmagman @stuartmorgan @louisehsu Any updates on this?

2024-01-13 22:01 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/example/ios/RunnerTests/FLTLocalAuthPluginTests.m
@OutdatedGuy We all have a lot of other things we're working on; if you want someone else to do this, you'll need to wait until one of us has time.

2024-01-23 20:16 UTC, stuartmorgan commented on packages/local_auth/local_auth_darwin/example/ios/RunnerTests/FLTLocalAuthPluginTests.m
I've pushed this change.

2024-01-23 20:17 UTC, stuartmorgan commented
This will need to be reconciled with main due to the change from iOS 11 to iOS 12 as a minimum version.

2024-02-07 22:48 UTC, jmagman approved these changes
LGTM!  Can you rebase and fix up the merge conflicts again, then we're ready to merge.  Really appreciate you tackling this, looking forward to the macOS support on top of this!

2024-02-07 22:51 UTC, jmagman commented on packages/local_auth/local_auth_darwin/darwin/local_auth_darwin.podspec
>  # To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
Actually this needs the `PrivacyInfo.xcprivacy` pulled in and `resource_bundles` path updated:
```
 -> local_auth_darwin (0.0.1)
    - NOTE  | url: The URL (https://pub.dev/packages/local_auth_darwin) is not reachable.
    - ERROR | [iOS] file patterns: The `resource_bundles` pattern for `local_auth_ios_privacy` did not match any file.
```

See https://github.com/flutter/packages/pull/5846/files#diff-3224e4fc5e9a47bae7d7c5dcc243e869174b97b0b4e8572a6e58fde8c0b3f5d5

2024-02-08 18:43 UTC, jmagman commented
Can you also switch
```
 Unknown directory "packages/local_auth/local_auth_ios" in CODEOWNERS
```
https://github.com/flutter/packages/blob/316bde0b3908ee4b6f6928476ec1b4ecba393e39/CODEOWNERS#L91

Hopefully almost done 🤞

2024-02-09 19:25 UTC, jmagman commented
@stuartmorgan can you take a look at this again?  Blocked on your change request.

2024-02-09 20:48 UTC, stuartmorgan approved these changes
LGTM!

2024-02-09 20:49 UTC, merged