[video_player] Call `super.dispose` last in README example
flutter/packages pull request #6051
Opened 2024-02-05 12:59 UTC by tp

As per https://api.flutter.dev/flutter/widgets/State/dispose.html

> Implementations of this method should end with a call to the inherited method, as in super.dispose().

2024-02-05 17:26 UTC, tarrinneal commented
Good catch on this! Our README code samples are pulled directly from code snippets in the example app and must match what is in the app to pass the repo_checks tests.

https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#readme-code

you can just manually change the snippet to match, or change the snippet and run the code I linked to.

You'll also need to update the changlelog and versioning for this package or the changes you added wont be synced to the published package.

https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates

2024-02-13 21:52 UTC, tarrinneal requested changes
Good catch on this! Our README code samples are pulled directly from code snippets in the example app and must match what is in the app to pass the repo_checks tests.

https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#readme-code

you can just manually change the snippet to match, or change the snippet and run the code I linked to.

You'll also need to update the changlelog and versioning for this package or the changes you added wont be synced to the published package.

https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates

2024-03-21 19:26 UTC, stuartmorgan commented
From triage: @tp, are you still planning on updating this PR to address the review comments above?

2024-03-22 15:48 UTC, tarrinneal commented
> @tarrinneal Thanks for the detailed explanation. I have updated the PR accordingly, and now only one job that fails across multiple open PRs (and seemingly unrelated) fails.

Yep, tree-status isn't one you need to worry about. I'll add this back into my queue! Thanks for fixing it up!

2024-03-28 02:13 UTC, tarrinneal approved these changes
thanks for putting the time into this!

2024-03-28 02:14 UTC, tarrinneal commented
@stuartmorgan for second review

2024-04-01 15:59 UTC, stuartmorgan requested changes

2024-04-01 15:59 UTC, stuartmorgan commented on packages/video_player/video_player/CHANGELOG.md
> +* Update example to call `super.dispose()` last
Updates

https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style

2024-04-01 15:59 UTC, stuartmorgan commented on packages/video_player/video_player/CHANGELOG.md
> +* Update example to call `super.dispose()` last
This is missing a period.

https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style

2024-04-03 20:25 UTC, stuartmorgan approved these changes

2024-04-04 11:50 UTC, stuartmorgan commented
Your rebase removed the version bump; PRs can't add changes to versions that have already been published.

2024-04-05 09:18 UTC, merged