Fix Example Ios from Pigeon + Update Readme
flutter/packages pull request #6237
Opened 2024-03-01 18:28 UTC by 4rthurmonteiro

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2024-03-05 10:28 UTC, tarrinneal requested changes
The "unnecessary code" serves a purpose elsewhere in our codebase, you should revert it's removal.

2024-03-05 10:28 UTC, tarrinneal commented on packages/pigeon/example/app/ios/Runner/AppDelegate.swift
> -
This code is here to provide example for our README, it shouldn't be removed.

2024-03-05 10:30 UTC, tarrinneal commented
> _Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots._
> 
> _List which issues are fixed by this PR. You must list at least one issue._
> 
> _If you had to change anything in the [flutter/tests](https://github.com/flutter/tests) repo, include a link to the migration guide as per the [breaking change policy](https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes)._

Also, please follow the instructions provided here.

2024-04-03 21:06 UTC, vashworth commented
@4rthurmonteiro Are you still working on this?

2024-05-08 18:00 UTC, stuartmorgan commented
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

2024-05-08 18:00 UTC, closed without merging