cc
flutter/packages pull request #6426
Opened 2024-03-28 17:44 UTC by tarrinneal

wip

2024-04-04 20:00 UTC, stuartmorgan commented
> removes double encode/decode on custom classes.

Per offline discussion I think we should adjust the PR description here, as well as the changelog. It's not that things were double-encoding custom classes, it's that we were making the encoding logic needlessly complex by calling ToList/FromList directly instead of letting the encoder do the encoding internally.

(This PR will actually make the byte encoding slightly *less* efficient; before a custom class was encoded as `<list type marker><list size><list elements>` and now it will be `<custom class type marker><list type marker><list size><list elements>`. Maybe that's why it was originally written the other way, but I don't think that's a worthwhile optimization for the conceptual complexity it adds.)

2024-04-09 19:30 UTC, stuartmorgan requested changes

2024-04-09 19:30 UTC, stuartmorgan commented on packages/pigeon/lib/objc_generator.dart
>  String _listGetter(String list, NamedType field, int index, String? prefix) {
This is only used in one place; now that it's one line we should just inline it at the call site. The string itself is pretty self-explanatory.

2024-04-09 19:30 UTC, stuartmorgan commented on packages/pigeon/lib/swift_generator.dart
>            if (field.type.isClass) {
This is now identical to the final `else`, just written slightly differently; they should be consolidated and normalized (either with everything using `fieldName`, or with `fieldName` eliminated in favor of `field.name`).

2024-04-09 19:30 UTC, stuartmorgan commented on packages/pigeon/lib/swift_generator.dart
> +          indent.writeln('$variableName = ${variableName}List as $fieldType');
Shouldn't these no longer have `List` in the name?

(Also, is this still actually different than the `else` branch?)

2024-04-09 19:30 UTC, stuartmorgan commented on packages/pigeon/lib/swift_generator.dart
> +        indent.writeln('let $variableName = $value as! $fieldType');
Is this different than the `else`?

2024-04-09 19:30 UTC, stuartmorgan commented on packages/pigeon/pigeons/core_tests.dart
> +  List list;
I think it's worth commenting on why this name doesn't match all the other ones, so someone doesn't think it's a mistake a change it back later.

2024-04-22 23:50 UTC, tarrinneal commented on packages/pigeon/example/app/android/app/src/main/kotlin/dev/flutter/pigeon_example_app/Messages.g.kt
> +@file:Suppress("UNCHECKED_CAST", "LocalVariableName", "ArrayInDataClass")
most of them are full file regardless, it gives "redundant suppression" errors.

2024-04-26 20:29 UTC, stuartmorgan commented
Now I remember why this error looked familiar: it's a bug in VS 2019, which was fixed in VS 2022.

We actually shouldn't still be using VS 2019 in CI, but it's going to be tricky to update that right now so I'll dig up the workaround. IIRC it will just require turning on exceptions for the test app.

2024-04-30 06:41 UTC, tarrinneal commented
> Now I remember why this error looked familiar: it's [a bug in VS 2019, which was fixed in VS 2022](https://developercommunity.visualstudio.com/t/stdany-doesnt-link-when-exceptions-are-disabled/376072).
> 
> We actually shouldn't still be using VS 2019 in CI, but it's going to be tricky to update that right now so I'll dig up the workaround. IIRC it will just require turning on exceptions for the test app.

Seems like it may be something else still...

2024-04-30 13:53 UTC, stuartmorgan commented
> > Now I remember why this error looked familiar: it's [a bug in VS 2019, which was fixed in VS 2022](https://developercommunity.visualstudio.com/t/stdany-doesnt-link-when-exceptions-are-disabled/376072).
> > We actually shouldn't still be using VS 2019 in CI, but it's going to be tricky to update that right now so I'll dig up the workaround. IIRC it will just require turning on exceptions for the test app.
> 
> Seems like it may be something else still...

Or it is that same problem, but I put the workaround on the example app binary when the failure is coming from a unit test file that's not compiled in that binary, and I need to change the build settings of the thing that was actually failing to compile 🤦🏻

2024-05-01 15:03 UTC, stuartmorgan approved these changes
LGTM! Just a few minor comments about possible simplifications.

2024-05-01 15:03 UTC, stuartmorgan commented on packages/pigeon/lib/swift_generator.dart
> +  if (type.baseName == 'Map') {
Maybe a comment in the code here for why Map needs special handling? It's not obvious to me what this change is for.

2024-05-06 11:55 UTC, merged