[webview_flutter] Add support for detecting process termination on Android - #130297
flutter/packages pull request #6508
Opened 2024-04-12 14:45 UTC by Sinishisimus

Added a new platform interface method to PlatformNavigationDelegate in webview_flutter_platform_interface setOnWebViewRenderProcessTerminated(ProcessTerminationDetails) which handles web view render process termination on Android, for details see: https://developer.android.com/reference/android/webkit/WebViewClient#onRenderProcessGone(android.webkit.WebView,%20android.webkit.RenderProcessGoneDetail)

This PR fixes the following issue: https://github.com/flutter/flutter/issues/130297

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2024-04-12 15:08 UTC, stuartmorgan commented
Thanks for the contribution! You haven’t checked off any of the items in the PR checklist above, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when that’s complete please feel free to mark the PR as ready for review.

2024-04-12 15:15 UTC, Sinishisimus commented
Hey @stuartmorgan I went through all the items in the checklist and implemented the changes needed. It could be that I missed something or that someting is off. This is where I would need yopur feedback. :)

2024-04-12 16:10 UTC, stuartmorgan commented
It does not appear that you followed https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins, which is causing almost everything in CI to fail.

2024-04-12 18:54 UTC, bparrishMines commented
Also, work on this will be blocked by https://github.com/flutter/flutter/issues/134777. The code that wraps the native function will need to be reworked after `webview_flutter_android` switches to the generator.

2024-04-26 10:49 UTC, stuartmorgan commented
> I can not figure out why.

Have you looked at the `stdout` for each of the failing steps? Each of them has an explanation of what the problem is.

2024-05-22 07:51 UTC, Sinishisimus commented
> @Sinishisimus Is this ready for review? It looks like there are still some minor `repo_checks` failures; is that the only reason it's still in Draft mode? (The version/changelog check isn't a big deal for the combo PR, but format and license should pass.)

Hey @stuartmorgan, yes, you are correct, the only reason why the PR is still in draft state is because of these minor `repo_checks` failures, which I haven't had time to address yet (but planing to address this this week hopefully). Can you maybe give some guidance how to quickly address the remainng issues you mentioned (but format and license should pass)?
I see olny Linux repo checks not passing https://github.com/flutter/packages/pull/6508/checks?check_run_id=24301966434

2024-05-22 17:11 UTC, bparrishMines commented
@Sinishisimus To fix formatting, you can run the tool from the root of the repository:

```bash
( cd script/tool/ ; dart pub get )
dart run script/tool/bin/flutter_plugin_tools.dart format
```

For the license and other failures, you can click on `details` and then `View more details on flutter-dashboard` of the `Linux repo_checks`. These should give you an explanation on how to fix them. You can ignore the failures for `CHANGELOG and version validation` and `federated safety check` for now since they should be fail until this PR is split.

2024-06-03 16:45 UTC, stuartmorgan requested changes
Where is the iOS implementation? Please see the original description of https://github.com/flutter/flutter/issues/130297, as well as https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#platform-support

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter/CHANGELOG.md
> +  For more details see: https://developer.android.com/reference/android/webkit/WebViewClient#onRenderProcessGone(android.webkit.WebView,%20android.webkit.RenderProcessGoneDetail)
We do not generally want to put Android-specific docs in the app-facing package. Our cross-platform abstraction needs to be understandable without going to platform-level docs.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter/CHANGELOG.md
> +## 4.8.1
New features require a minor version bump, per semver.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter/lib/src/navigation_delegate.dart
> +  /// Invoked when a the given WebView's render process has exited (Android only).
Same.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/CHANGELOG.md
> +## 3.16.3
Minor version, per previous comment.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/CHANGELOG.md
> +* Adds onWebViewRenderProcessTerminated WebViewClient callback on Android to support
Changelog entries in an Android-specific package don't need to say "on Android".

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/lib/src/android_webview.dart
> +  /// Notify host application that the given WebView's render process has exited (Android only).
This package is Android-only.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/lib/src/android_webview.dart
> +  /// Multiple WebView instances may be associated with a single render process;
Please don't copy and paste large amounts of text from the Android docs.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/lib/src/android_webview.dart
> +/// This class provides more specific information about why the webview render process exited (Android only).
As above, no need to say "Android only".

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/lib/src/android_webview.dart
> +class ProcessTerminationDetails {
Why is the same class being declared in two different packages?

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
> +## 2.10.1
Minor version.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_navigation_delegate.dart
> +  /// Notify host application that the given WebView's render process has exited.
Please use the same "Invoked when ..." structure as all the other comments here.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/process_termination_details.dart
> +  final bool didCrash;
What would a platform implementation that didn't have access to this information pass? It seems like this needs to be an enum, where one of the options is "unknown".

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/process_termination_details.dart
> +  /// Returns the renderer priority that was set at the time that the renderer exited.
This is extremely Android-specific, so should not be in this package. If it's actually needed it should be in an Android-specific subclass, but it's not clear to me that there's a plausible use case for this data.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_web/example/pubspec.yaml
> +# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
These changes can be reverted in packages that have no other changes.

2024-06-03 16:45 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
> +* Adds `decidePolicyForNavigationResponse` to internal WKNavigationDelegate to support the
This is copy/pasted from a previous changelog entry, and is unrelated to the PR.

2024-06-27 18:33 UTC, yaakovschectman commented
From Android triage: We will close this for now to get it off of our review queue while there are open comments and merge conflicts. Please reopen or open a new PR if you get back to this.

2024-06-27 18:33 UTC, closed without merging