[flutter_adaptive_scaffold] Allows for the animation duration to be adjusted using SlotLayout.from()
flutter/packages pull request #6510
Opened 2024-04-12 16:10 UTC by oravecz-jpmc

Added `duration` to the `SlotLayoutConfig` constructor and `from()` method. This allows a user to specify the duration of the in/out animations which they can already supply.

The default animation of 1 second is nice for demos where a slowed down animation helps to show the behavior, but it is (arguably?) way too slow for an application where one wants a snappy animation effect.

*List which issues are fixed by this PR. You must list at least one issue.*

Fixes https://github.com/flutter/flutter/issues/112938

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

No change to tests

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [test-exempt] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2024-04-12 19:08 UTC, oravecz-jpmc commented
Added test case to ensure animation duration is being applied

2024-04-26 15:28 UTC, gspencergoog approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

2024-05-24 17:12 UTC, stuartmorgan commented on packages/flutter_adaptive_scaffold/lib/src/slot_layout.dart
> +  /// The amount of time taken by the execution of the in and out animations
This comment is missing the period at the end.

2024-05-24 17:14 UTC, stuartmorgan commented on packages/flutter_adaptive_scaffold/test/adaptive_layout_test.dart
> +MediaQuery slot(double width, int durationMs, WidgetTester tester) {
Why is this an int with the type in the name rather than a `Duration` that would directly encode unit information in the code?

2024-06-04 19:56 UTC, stuartmorgan commented
@oravecz-jpmc Is this ready for re-review?

2024-06-24 15:23 UTC, stuartmorgan approved these changes

2024-06-24 15:25 UTC, stuartmorgan requested changes
This isn't passing CI, including `analyze`; that will need to be resolved before re-review.

2024-06-24 15:25 UTC, stuartmorgan commented on packages/flutter_adaptive_scaffold/CHANGELOG.md
> +## 0.1.11+1
I missed that the version change itself was lost from the PR, which is part of why CI is failing.

2024-06-24 18:14 UTC, stuartmorgan approved these changes

2024-06-24 18:14 UTC, merged