Update `web_benchmarks` package to properly support wasm.
flutter/packages pull request #6970
Opened 2024-06-21 20:47 UTC by eyebrowsoffire

This fixes the web_benchmarks package so it can compile and run apps with wasm. It also updates our CI steps to use a newer version of Chrome so that WasmGC works properly.

2024-06-21 22:02 UTC, yjbanov approved these changes
![lgtm](https://user-images.githubusercontent.com/211513/32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d.png)

2024-06-24 20:11 UTC, stuartmorgan requested changes

2024-06-24 20:11 UTC, stuartmorgan commented on packages/web_benchmarks/CHANGELOG.md
> +* Support for running benchmarks with the wasm compilation target.
"Adds support for [...]", per the repo CHANGELOG style guide.

2024-06-24 20:11 UTC, stuartmorgan commented on packages/web_benchmarks/lib/src/compilation_options.dart
> -  const CompilationOptions({
Removing a constructor from a public class is a breaking change, and all of our packages follow semver. If you want to remove this, the package needs a major version bump.

2024-06-25 16:46 UTC, stuartmorgan commented on packages/web_benchmarks/CHANGELOG.md
This needs a description of the breaking changes; see https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style

2024-06-25 17:02 UTC, stuartmorgan approved these changes

2024-06-27 14:26 UTC, merged