[webview_flutter_web] Add support for the credentialless attribute. (…
flutter/packages pull request #7097
Opened 2024-07-10 19:23 UTC by uldall

…#151557)

This PR makes it possible to specify whether the `<iframe>` should have the attribute `credentialless` set to true or false. 

[#151557](https://github.com/flutter/flutter/issues/151557)

## Pre-launch Checklist

- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [ x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ x] I signed the [CLA].
- [ x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x ] I [linked to at least one issue that this PR fixes] in the description above.
- [ x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [x ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2024-07-10 19:37 UTC, uldall commented
Example usage:
```
    late final PlatformWebViewControllerCreationParams params;
    if (WebViewPlatform.instance is WebWebViewPlatform) {
      params = WebWebViewControllerCreationParams(
        iFrameCredentialless: true,
      );
    } else {
      params = const PlatformWebViewControllerCreationParams();
    }

    _webViewController = WebViewController.fromPlatformCreationParams(params);
```

2024-07-10 19:54 UTC, uldall commented
Example of how it looks when the attribute is added:
![image](https://github.com/flutter/packages/assets/628383/f537773f-9acf-47f5-826c-79c70778f72a)

2024-07-10 21:40 UTC, stuartmorgan commented
Thanks for the contribution! You’ve checked boxes in the PR checklist above that are not reflected in this PR, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when the checklist reflects the state of the PR as posted please feel free to mark it as ready for review.

2024-07-11 17:40 UTC, uldall commented
> Thanks for the contribution! You’ve checked boxes in the PR checklist above that are not reflected in this PR, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when the checklist reflects the state of the PR as posted please feel free to mark it as ready for review.

I have added tests and comments now. I am not sure about whether I am supposed to update the pubspec.yaml and CHANGELOG.md? Sorry about the potentially stupid question. This is my first PR on the Flutter project.

2024-07-20 06:05 UTC, uldall commented
Would it be preferable if I changed this PR to use a Map<String, String> of attributes instead so it became more generic?

2024-08-06 19:55 UTC, stuartmorgan commented
From triage: Ping @ditman on the design question above.

2024-09-10 21:04 UTC, ditman requested changes
Small nit with setting the `credentialless` attribute only when really needed.

2024-09-10 21:04 UTC, ditman commented on packages/webview_flutter/webview_flutter_web/lib/src/web_webview_controller.dart
> +              'credentialless', iFrameCredentialless ? 'true' : 'false'),
Setting `credentialless` to any value results it in being `true`

* https://jsfiddle.net/ditman/obufjvtk/

Set the attribute only `iFrameCredentialless` is `true`.

2024-09-10 21:06 UTC, ditman commented
> Would it be preferable if I changed this PR to use a Map<String, String> of attributes instead so it became more generic?

@uldall I think it's better that we do this using the type safety of Dart and `package:web` rather than a _stringly_ typed map :)

(PS: `credentialless` is only supported in Chrome browsers for now, we may need to add a note to the parameter itself so users are aware of this limitation?)

2024-10-01 19:57 UTC, stuartmorgan commented
@uldall Are you still planning on updating this PR based on the feedback above?

2024-10-13 12:41 UTC, uldall commented
I am not sure why GitHub closed my PR just because I updated my fork..

2024-12-03 20:52 UTC, stuartmorgan commented
Since this is marked as a draft and hasn't been updated in several months, I’m going to close it so that our PR queue reflects active PRs. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

2024-12-03 20:52 UTC, closed without merging