[camera] Support image streams on Windows platform
flutter/packages pull request #7220
Opened 2024-07-25 23:09 UTC by jlundOverlay

Adds support to the to the camera plugin for streaming frames on windows as implemented in https://github.com/flutter/packages/pull/7067

Fixes https://github.com/flutter/flutter/issues/97542

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2024-07-25 23:11 UTC, jlundOverlay commented
Are we better off just removing the assertion all together, seems redundant to limit what non federated packages can do?

2024-07-25 23:50 UTC, loic-sharma commented on packages/camera/camera/lib/src/camera_controller.dart
> +        defaultTargetPlatform == TargetPlatform.windows);
Could you also update the comment above, on line 483?

2024-07-25 23:50 UTC, loic-sharma commented on packages/camera/camera/lib/src/camera_controller.dart
> +        defaultTargetPlatform == TargetPlatform.windows);
Could you also update the comment above on line 522?

2024-07-25 23:52 UTC, loic-sharma approved these changes
LGTM.

For second reviewer: don't merge until https://github.com/flutter/packages/pull/7067 lands and `camera_windows 0.2.5` is published.

2024-07-25 23:56 UTC, loic-sharma commented
> Are we better off just removing the assertion all together, seems redundant to limit what non federated packages can do?

Excellent question. Personally, I think it's good to keep these checks. This tells app developers if they use an API that's unsupported on a specific platform, which is a common mistake. If a federated platform package wants to add a feature, they can ask us to remove a particular check to allowlist them.

2024-07-30 23:52 UTC, bparrishMines approved these changes
LGTM (it also looks like the windows implementation has landed)

> Are we better off just removing the assertion all together, seems redundant to limit what non federated packages can do?

Typically you would be correct, but the camera plugin still uses a [default implementation](https://github.com/flutter/packages/blob/main/packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart#L28) for `CameraPlatform`. For newer plugins, we don't add this check since the platform interface would throw an error  by default if the method wasn't supported.

2024-08-16 17:29 UTC, cbracken commented
Are we good to land this now?

2024-08-27 19:53 UTC, stuartmorgan commented
@jlundOverlay Are you still planning on updating this PR?

2024-08-27 23:01 UTC, jlundOverlay commented
Have fixed the merge conflicts, should be good to go.

2024-08-28 09:53 UTC, stuartmorgan requested changes
Looking at this PR in more detail: it does not appear that the bug I flagged [here](https://github.com/flutter/packages/pull/7067#discussion_r1693929891) was ever fixed. We should not enable this feature when it will fail to send responses and violate the contract of the engine APIs it uses.

2024-08-28 09:58 UTC, stuartmorgan commented
> > Are we better off just removing the assertion all together, seems redundant to limit what non federated packages can do?
> 
> Excellent question. Personally, I think it's good to keep these checks. This tells app developers if they use an API that's unsupported on a specific platform, which is a common mistake. If a federated platform package wants to add a feature, they can ask us to remove a particular check to allowlist them.

We should fix this via [this pattern](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#api-support-queries) which is our preferred approach; the hard-coded platform checks are a legacy of pre-federation approaches. Rather than update the hard-coding, the much better fix here would be to add a new platform interface method to query for streaming support, update the supported platforms to return `true` for it, and then update the app-facing package to require those minimum versions of the implementation packages (to avoid regressions) and gate on that check instead of platform.

2024-10-01 19:53 UTC, stuartmorgan commented
@jlundOverlay Are you still planning on updating this to address the issue with missing responses?

If not, we should revert the underlying PR, as that code is not correct, and would cause serious issues if ever exposed.

2024-10-27 14:24 UTC, yoongyo commented
Please keep making progress.

2024-10-27 15:55 UTC, gamelaster commented
@yoongyo it seems as the original author of patch was doing that as part of their job, and maybe they don't work anymore. I think it would be wise to look for someone, who can continue working on this.

Of course, writing this is easy, but I already tried to put this into my job's todo-list, although, in the end, we will not use this feature :frowning_face: .

2024-10-29 11:57 UTC, stuartmorgan commented
Closing in light of https://github.com/flutter/packages/pull/7951 and the lack of response here. If you decided to revisit this feature in the future, please feel free to open a new PR!

2024-10-29 11:57 UTC, closed without merging