Fixes TreeSliver collapsing not working
flutter/packages pull request #7474
Opened 2024-08-21 22:58 UTC by Mairramer

Fixes a same error of https://github.com/flutter/flutter/issues/153418

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2024-08-22 18:57 UTC, Piinks commented on packages/two_dimensional_scrollables/test/tree_view/tree_test.dart
> +        'TreeSliverNode should close all children when collapsed when animation is completed',
Can you update the language here? This seems to be referring to the 1D version in the framework.

2024-08-22 18:59 UTC, Piinks commented
Can you also update the title of this PR to reflect this package? It currently refers to the framework change, not this one. Also, the PR template for this repo is different from the framework. For example, it specifies the title of the PR should start with the [name_of_package].

2024-09-11 08:34 UTC, lbgitjp commented on packages/two_dimensional_scrollables/lib/src/tree_view/tree.dart
> +          controller.reverse();
hwo about change below code
https://github.com/flutter/packages/blob/bb53e5d536aeba377b5f8877ad735973293ae200/packages/two_dimensional_scrollables/lib/src/tree_view/tree.dart#L936-L945
to

```
      switch (node._expanded) {
        case true:
          // Expanding
          controller.forward();
        case false:
          // Collapsing
          controller.reverse();
      }
```

2024-09-11 08:35 UTC, lbgitjp commented on packages/two_dimensional_scrollables/lib/src/tree_view/tree.dart
> +              }
how about remove 'if' and chang the code to below:
```
              setState(() {
                _unpackActiveNodes();
              });
```

2024-09-11 08:38 UTC, lbgitjp commented on packages/two_dimensional_scrollables/lib/src/tree_view/tree.dart
> +              }
how about remove 'if' and chang the code to below:
```
              setState(() {
                _unpackActiveNodes();
              });
```

2024-09-11 19:24 UTC, Piinks commented on packages/two_dimensional_scrollables/test/tree_view/tree_test.dart
> +    testWidgets(
Similar to the framework change, this test does not fail when run without the code change. It should so it verifies the fix works as expected, and prevents us from regressing in the future.

2024-09-11 19:24 UTC, Piinks requested changes
This will need updated tests to move forward.

2024-09-23 11:44 UTC, Mairramer commented
@Piinks Same of comment https://github.com/flutter/flutter/pull/153438#issuecomment-2363614393.

2024-10-15 20:15 UTC, Piinks commented on packages/two_dimensional_scrollables/test/tree_view/tree_test.dart
> +      await tester.runAsync(() async {
This change made this a valid regression test, can you share why it needed to runAsync?

2024-10-15 20:42 UTC, Piinks commented on packages/two_dimensional_scrollables/test/tree_view/tree_test.dart
> +      await tester.runAsync(() async {
Answered in related PR https://github.com/flutter/flutter/pull/153438#discussion_r1801888873

2024-10-15 20:42 UTC, Piinks approved these changes
LGTM

2024-10-17 18:10 UTC, merged