[google_maps_flutter_web] set icon anchor for markers
flutter/packages pull request #8077
Opened 2024-11-13 23:35 UTC by veronikalaskova

*Fixes issue where a marker anchor is ignored on flutter web google maps.*

*https://github.com/flutter/flutter/issues/80578*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2024-11-15 03:42 UTC, frapeti commented
+1

Working as expected here, thank you!

2024-11-26 02:07 UTC, JamesMcIntosh commented
Hi @ditman, could this bug fix please be merged and released?

2025-01-14 20:56 UTC, stuartmorgan commented
From triage: @ditman, this is waiting on your review.

2025-02-21 06:51 UTC, JamesMcIntosh commented
Hi @ditman, would you be available to review this PR? If you're too busy, would it be possible to delegate it to someone else?

2025-02-21 18:03 UTC, stuartmorgan requested changes
This is straightforward enough that @tarrinneal and I should be able to take over the review.

2025-02-21 18:03 UTC, stuartmorgan commented on packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/markers_test.dart
> +        anchor: const Offset(1.5, 2),
Anchors are in a normalized coordinate space; why are these both more than 1.0?

2025-02-21 18:24 UTC, tarrinneal approved these changes
LGTM once Stuarts comments are addressed.

2025-02-24 02:35 UTC, veronikalaskova commented on packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/markers_test.dart
> +        anchor: const Offset(1.5, 2),
I'm not quite sure what you mean by this comment. What is it normalized to?

The default value for anchor is const Offset(0.5, 1). 
In some scenarios the user may want the offset to be different. Using a different offset for the second marker proves the different variable doesn't get ignored.

2025-02-24 21:54 UTC, veronikalaskova commented on packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/markers_test.dart
> +        anchor: const Offset(1.5, 2),
An example (from our project) to use an anchor outside the bounds would be positioning 2 markers in relation to one another. Eg a point (user's position) marker and a label for that point marker where the label needs to be offset from the marker and positioned lower on the y axis of the map.

2025-03-03 16:19 UTC, stuartmorgan requested changes

2025-03-03 16:19 UTC, stuartmorgan commented on packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
>  * Updates minimum supported SDK version to Flutter 3.22/Dart 3.4.
Please see https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#updating-a-changelog-that-has-a-next

This is why `repo_checks` is failing.

2025-03-03 16:20 UTC, stuartmorgan commented
You'll need to merge in the latest `main` so that the `analyze` CI steps pass.

2025-03-07 18:46 UTC, stuartmorgan approved these changes
LGTM

2025-03-07 19:12 UTC, merged