[local_auth] Allow empty localizedReason for Android
flutter/packages pull request #8115
Opened 2024-11-17 10:06 UTC by Luciferx86

localizedReason should be optional for Android. There could be use case where we only want to show a single piece of text on the biometric prompt. Currently showing 2 pieces of texts is mandatory.

## Proposal

Only set the description parameter to the BiometricPrompt if a non empty String is passed in the call.

code:

AuthenticationHelper.java

use
```
.setDescription(strings.getReason().isEmpty() ? null : strings.getReason())
```

instead of

```
.setDescription(strings.getReason())
```

** screenshots attached in the original issue

Related: https://github.com/flutter/flutter/issues/116885

## Pre-launch Checklist

- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [ x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ x] I signed the [CLA].
- [ x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ x] I [linked to at least one issue that this PR fixes] in the description above.
- [ x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ x] I updated/added relevant documentation (doc comments with `///`).
- [ x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2024-11-17 11:39 UTC, stuartmorgan requested changes
Thanks for the contribution!

This PR makes the Android implementation inconsistent with the public documentation of `authenticate`, which says (at both the app-facing and platform interface level) that the parameter must not be empty. That would mean that only people who read the implementation source would know that they could do the opposite of what the docs say, which is not how we would want to land this.

A complete fix needs to update the docs on those methods, as well as provide clients a runtime way of knowing whether or not the current platform requires a non-empty reason, via a [support query](https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#api-support-queries). So this needs a new platform interface method, called something like `requiresLocalizedReason()`, and for that to be wired up in the app-facing package as part of changing the documention for `authenticate`.

2024-11-18 04:20 UTC, Luciferx86 commented
I understand that there needs to be a method like `requiresLocalizedReason()` for all the platforms, and for `android` in particular, this method will return false.

So to make this work, I would be required to update the documentation for `authenticate` method, as well as override this method in all platform implementations? 

Also implementation for authenticate then becomes something like?

```dart
if(requiresLocalizedReason()){
assert(localizedReason.isNotEmpty);
}
```

Is this implementation correct, or you had something else in mind? @stuartmorgan

2024-11-25 15:41 UTC, stuartmorgan commented
> as well as override this method in all platform implementations?

Since there needs to be a default implementation that returns `true` for backwards compatibility, it only actually needs to be overridden in the Android implementation.

> Also implementation for authenticate then becomes something like?
> 
> ```dart
> if(requiresLocalizedReason()){
> assert(localizedReason.isNotEmpty);
> }
> ```

The assertions are currently at the platform implementation package level; every platform implementation already knows whether it needs the assertion or not, without a new conditional.

2025-01-14 20:56 UTC, stuartmorgan commented
@Luciferx86 Are you still planning on updating this based on the review discussion above?

2025-02-04 20:56 UTC, stuartmorgan commented
Thank you for your contribution. Since there are outstanding comments but the PR hasn’t been updated in several months, I’m going to close it so that our PR queue reflects active PRs. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

2025-02-04 20:56 UTC, closed without merging