[vector_graphics] Allow transition between placeholder and loaded image to have an animation
flutter/packages pull request #8195
Opened 2024-11-27 17:50 UTC by raju8000

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*
[Issue #158857](https://github.com/flutter/flutter/issues/158857)

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

2024-11-29 08:25 UTC, raju8000 commented
@stuartmorgan Can you review this? 
Thanks.

2024-12-13 16:15 UTC, stuartmorgan commented
@jonahwilliams Are these package's PRs being included in engine PR triage?

2024-12-16 21:26 UTC, jonahwilliams commented
They were not

2024-12-16 21:27 UTC, jonahwilliams requested changes

2024-12-16 21:27 UTC, jonahwilliams commented on packages/vector_graphics/lib/src/vector_graphics.dart
> +  Duration transitionDuration = const Duration(milliseconds: 500),
This doesn't just allow the transition, it forces it on for all apps. should this be opt in if a transition duration is specififed?

2025-01-06 19:30 UTC, jonahwilliams requested changes
I still see the default duration.

2025-01-18 21:48 UTC, jonahwilliams requested changes

2025-01-18 21:48 UTC, jonahwilliams commented on packages/vector_graphics/lib/src/vector_graphics.dart
> +  Duration transitionDuration = const Duration(milliseconds: 500),
To clarify, by providing a default value here and having the value be non-nullable, you will make all vector graphics fade in over 0.5 seconds. You must change this to be nullable with a null default or I will not accept the change

2025-01-27 22:39 UTC, jonahwilliams commented on packages/vector_graphics/lib/src/vector_graphics.dart
> +      child = widget.placeholderBuilder != null
Instead of the double nested ternary please right a helper function and/or some if statements.

2025-02-05 01:02 UTC, jonahwilliams approved these changes
LGTM

2025-02-05 01:07 UTC, domesticmouse approved these changes

2025-02-05 01:09 UTC, merged