[in_app_purchase] Update Play Billing library to 7.1.1
flutter/packages pull request #8218
Opened 2024-12-03 22:26 UTC by mchudy

Updates Play Billing Library to the latest version 7.1.1. Exposes new APIs as per [release notes](https://developer.android.com/google/play/billing/release-notes):
- Adds Dart representation of `ProductDetails.InstallmentPlanDetails`
- Adds Dart representation of `PendingPurchasesParams` and removes the deprecated `enablePendingPurchases` method on `BillingClientWrapper` (breaking change)
- Adds Dart representation of `Purchase.PendingPurchaseUpdate`
- Removes the deprecated `ProrationMode` as it has been removed from the native library (breaking change)

This PR introduces breaking changes in `in_app_purchase_android`, but does not introduce any breaking changes on the platform interface level.

Fixes https://github.com/flutter/flutter/issues/147394

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I [linked to at least one issue that this PR fixes] in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2024-12-17 20:43 UTC, stuartmorgan commented
@reidbaker Ping on this review

2024-12-18 19:37 UTC, reidbaker commented
@gmackall I am not going to get to this. Deferring to you for review.

2025-01-06 16:42 UTC, wph144 commented
The billingClient version upgrade process must proceed as quickly as possible. 
Older versions of billingClient cause a low probability of missing payments after a certain period of time. 
This may result in cases where the consumer makes a payment but does not receive the service for that payment, so the billingClient version upgrade must be done quickly. 

Currently, in_app_purchase 3.2.0 is using billingClient 6.2.0,
and billingClient 7.0.0 version was distributed in May 2024, 
so it has now taken more than 7 months. 
I hope this gets merged quickly.

2025-01-06 20:31 UTC, gmackall reviewed
Mostly LGTM, added a couple comments. Sorry for the delay on review

2025-01-06 20:31 UTC, gmackall commented on packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/BillingClientFactory.java
> +      Messages.PendingPurchasesParams pendingPurchasesParams);
It looks like there is an existing convention of naming our versions of the `BillingClient` classes `Platform$ExsitingClassName` and then defining translation between our version and the original version in [`Translator.java`](https://github.com/flutter/packages/blob/a4e540f7160dc9ea82f9be7d6d42d94d4208a81c/packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java).

Is there a reason you adopted this convention for `Messages.PlatformInstallmentPlanDetails` but not for `Messages.PendingPurchasesParams`? If not, can you adopt both of these conventions for this `Messages.PendingPurchasesParams` as well (i.e., rename to `PlatformPendingPurchasesParams`, and then contain all translation code in that one place and reference it in `BillingClientFactoryImpl` below?).

2025-01-06 20:31 UTC, gmackall commented on packages/in_app_purchase/in_app_purchase_android/android/src/test/java/io/flutter/plugins/inapppurchase/BillingClientFactoryImplTest.java
> +    // No logic to verify just ensure creation works.
extreme nit
```suggestion
    // No logic to verify, just ensure creation works.
```

2025-01-06 20:31 UTC, gmackall commented on packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.dart
> +/// Represents a pending change/update to the existing purchase.
nit: include docs links for classes that are direct wrappers
https://developer.android.com/reference/com/android/billingclient/api/Purchase.PendingPurchaseUpdate

2025-01-06 20:31 UTC, gmackall commented on packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/subscription_offer_details_wrapper.dart
> +/// Represents additional details of an installment subscription plan.
nit: add docs link

2025-01-06 20:57 UTC, mchudy commented on packages/in_app_purchase/in_app_purchase/CHANGELOG.md
> +- Updates minimum supported SDK version to Flutter 3.19/Dart 3.3.
Oh, sorry, yeah that was some autoformatting from VSCode

2025-01-06 23:04 UTC, mchudy commented on packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/BillingClientFactory.java
> +      Messages.PendingPurchasesParams pendingPurchasesParams);
Yeah, no reason for that, I missed that for some reason. It's fixed now.

2025-01-08 23:46 UTC, mchudy commented
CI is complaining about versioning, but I believe we should first publish the new version of in_app_purchase_android and only once that lands on pub update the dependency in the base package? Or can this be handled inside a single PR?

2025-01-09 13:06 UTC, stuartmorgan commented
> CI is complaining about versioning, but I believe we should first publish the new version of in_app_purchase_android and only once that lands on pub update the dependency in the base package? Or can this be handled inside a single PR?

See https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changing-federated-plugins for the process of landing a multi-package PR with interdependencies.

2025-01-09 13:11 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
> +  * Bumps `minSdk` to 21.
This would be a breaking change for `in_app_purchase` when rolling the dependency there; we strongly prefer not dropping OS support before the SDK itself.

In this case, Flutter 3.24+ only supports Android SDK 21+, so the way to make this change would be to update the plugin's min SDK version to 3.24, which makes this no longer a breaking change.

2025-01-14 18:33 UTC, gmackall approved these changes
LGTM, @stuartmorgan or @bparrishMines would either of you like to do the secondary review?

2025-01-15 16:17 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/pending_purchases_params_wrapper.dart
> +  @Deprecated('JSON serialization is not intended for public use, and will '
Why are we adding new code that is pre-deprecated?

The reason other classes had JSON serialization is that they were being serialized as JSON to send over the method channel. The reasons it's deprecated in all those classes is that we don't do that any more, because we use Pigeon. It was only left in place was to avoid a breaking change on the off-chance someone was using it for other reasons, since it was part of the public interface.

2025-01-15 16:17 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
> +* **BREAKING CHANGES**:
Since we are doing a breaking change, this seems like a good opportunity to rip out all the pre-Pigeon `JsonSerializable` code that was deprecated previously. @gmackall is there any reason not to include that here?

2025-01-16 14:55 UTC, mchudy commented on packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
> +* **BREAKING CHANGES**:
Sounds like a good idea, I have one question though. E.g. `BillingResponseConverter` was used to map from raw ints (Android defined constants) to public-facing `BillingResponse` enum. Naive approach would be to introduce a new function in `pigeon_converters.dart`:

```dart
BillingResponse billingResponseFromPlatformResponseCode(int responseCode) {
  return switch (responseCode) {
    -3 => BillingResponse.serviceTimeout,
    -2 => BillingResponse.featureNotSupported,
    -1 => BillingResponse.serviceDisconnected,
    0 => BillingResponse.ok,
    1 => BillingResponse.userCanceled,
    2 => BillingResponse.serviceUnavailable,
    3 => BillingResponse.billingUnavailable,
    4 => BillingResponse.itemUnavailable,
    5 => BillingResponse.developerError,
    6 => BillingResponse.error,
    7 => BillingResponse.itemAlreadyOwned,
    8 => BillingResponse.itemNotOwned,
    12 => BillingResponse.networkError,
    _ => BillingResponse.error,
  };
}
```

That looks a bit sketchy to me though as we have to deal with those hardcoded constants in Dart. Should we perhaps change the definition of `PlatformBillingResult` in Pigeon contract and introduce a new `PlatformBillingResponse` enum as part of this refactoring? If the mapping is performed on Java side we can refer to constants defined in the library so the code is more maintainable. Correct me if I'm wrong please.

2025-01-16 15:35 UTC, stuartmorgan commented on packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
> +* **BREAKING CHANGES**:
> Should we perhaps change the definition of `PlatformBillingResult` in Pigeon contract and introduce a new `PlatformBillingResponse` enum as part of this refactoring? If the mapping is performed on Java side we can refer to constants defined in the library so the code is more maintainable.

Yes, that's definitely what we want to do. The fact that we are still using `BillingResponseConverter().fromJson` in `pigeon_converters.dart` was a mistake on my part; I did an initial shallow conversion from manual method channels to Pigeon and then went back and converted objects more deeply to Pigeon structures in follow-ups, but missed this. We strongly prefer the clarity and safety of doing a Java constant -> Pigeon enum conversion in Java, then Pigeon enum -> Dart enum conversion in Dart, even though doing so is more verbose.

2025-01-17 12:28 UTC, mchudy commented on packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
> +* **BREAKING CHANGES**:
I refactored this and introduced new enum in Pigeon contracts. I also noticed that the representation of https://developer.android.com/reference/com/android/billingclient/api/BillingClient.FeatureType was very outdated so I made it match the current API. As it removes two variants it's another breaking changes, but I think it would be good to include this with those other breaking changes.

2025-01-17 15:35 UTC, reidbaker approved these changes
Hold on merging for @stuartmorgan's approval. Specifically if all of the json removal work he wants removed has been done.

2025-01-17 20:59 UTC, stuartmorgan reviewed
Awesome, thanks for all of this cleanup!

It looks like `bulid.yaml` can be removed, as well as the `json_annotation` and `json_serializable` dependencies in `pubspec.yaml`, but that's all I see that's left.

2025-01-17 21:24 UTC, stuartmorgan requested changes
> Hold on merging for @stuartmorgan's approval.

This PR can't actually be landed as-is; it's saying that it bumps the `in_app_purchase_android` version in `in_app_purchase`, but doesn't (and can't in this PR).

I'm going to put a request-changes flag on the PR just to make sure nobody accidentally lands it as is. This is ready to be split into two PRs though (with the minor changes in my previous comment) for landing.

2025-01-20 09:55 UTC, mchudy commented
I removed the JSON dependencies and moved the `in_app_purchase` package part to https://github.com/flutter/packages/pull/8463

2025-01-20 15:31 UTC, stuartmorgan approved these changes
LGTM!

2025-01-20 15:32 UTC, merged