[shared_preferences] Tool for migrating from legacy shared_preferences to shared_preferences_async
flutter/packages pull request #8229
Opened 2024-12-04 22:28 UTC by tarrinneal

2024-12-14 00:25 UTC, tarrinneal commented
@stuartmorgan this is ready for review now, though it will be waiting for https://github.com/flutter/packages/pull/8296 to land

2025-01-03 17:15 UTC, stuartmorgan requested changes
The README should be updated to explain this, in place of the discussion about manual migration.

2025-01-03 17:15 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_migration_tool_test.dart
> +        await preferences.setBool(boolKey, testBool);
What do you think of [this version](https://github.com/stuartmorgan/packages/blob/migration-alt-tests/packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_migration_tool_test.dart)?

2025-01-03 17:15 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +/// A tool to migrate from the legacy SharedPreferences system to
Similarly, I would say "Migrates preferences from [...]" so there's no potential confusion that this is a stand-alone tool that has to be packaged and run.

2025-01-03 17:15 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +/// The [migrationCompletedKey] is a key that will be used to check if the migration
I think this should be explicit about the fact that the key is stored in the target preference system, not the legacy preference system.

2025-01-03 17:15 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +  bool clearLegacyPreferences = false,
This appears to not do anything?

2025-01-03 17:15 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +        } catch (_) {} // Pass over Lists containing non-String values.
Do you want to catch *all* exceptions here, or only cast exceptions? The comment implies the former, but it does the latter which could silently swallow other problems.

2025-01-03 17:15 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +Future<void> migrateLegacySharedPreferencesToSharedPreferencesAsync(
This should probably be called `migrateLegacySharedPreferencesToSharedPreferencesAsyncIfNecessary`. And the docs should be explicit that it's safe to call on every launch as it will do nothing if migration has already happened.

2025-01-03 17:15 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +  keys = legacySharedPreferencesInstance.getKeys();
Why are the keys being set twice?

2025-01-03 18:10 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +  bool clearLegacyPreferences = false,
forgot about that. Is this a feature that's worth adding? I hadn't yet as it seemed like it could be problematic.

2025-01-03 18:14 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +  bool clearLegacyPreferences = false,
We could wait and see if anyone asks. On one hand, I would generally expect a migration to move data instead of duplicating it. On the other hand, it shouldn't be a lot of data.

My one real hesitation here is that if someone isn't using an allow list, on most platforms this would mean that an unprefixed new-style prefs object would be loading all the old prefs too.

2025-01-03 19:45 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_migration_tool_test.dart
> +    void runTests(
Better to duplicate the tests then? I just wanted to ensure equivalent coverage without unnecessary duplication. I can see how it's a bit convoluted though.

2025-01-03 19:48 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_migration_tool_test.dart
> +        await preferences.setBool(boolKey, testBool);
This makes sense, I guess I just don't like calling code before it's defined. This does seem clearer.

2025-01-03 19:50 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_migration_tool_test.dart
> +    void runTests(
The version I proposed below makes the logic more directly traceable; it seemed like a reasonable compromise between trying to avoid spooky action at a distance (e.g., nested layers of `setUp` scattered through the file) without adding duplication.

2025-01-07 18:19 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences/lib/tools/legacy_to_async_migration_tool.dart
> +  bool clearLegacyPreferences = false,
It also means that items not set by our plugin would get deleted. Potentially if not used carefully (or written carefully) it could write to the same file, then delete the prefs it just wrote.

2025-01-08 21:32 UTC, stuartmorgan requested changes
`<seinfeldmeme>`You thumbs-up'd my comment about updating the README, but you didn't update the README`</seinfeldmeme>` 🙂

2025-01-09 20:46 UTC, tarrinneal commented
> `<seinfeldmeme>`You thumbs-up'd my comment about updating the README, but you didn't update the README`</seinfeldmeme>` 🙂

I use the resolve button to track work I have or haven't done yet, since that comment isn't resolvable, I missed it.

2025-01-13 19:41 UTC, tarrinneal commented
> `<seinfeldmeme>`You thumbs-up'd my comment about updating the README, but you didn't update the README`</seinfeldmeme>` 🙂

RESOLVED

2025-01-23 20:01 UTC, stuartmorgan requested changes

2025-01-23 20:01 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/example/lib/main.dart
> +        prefs, sharedPreferencesOptions, 'migrationCompleted');
Since this is a README snippet, where there's no context about the arguments, let's make a
`const String migrationCompletedPrefKey = 'migrationCompleted'` as the previous line, and then use that variable here, so it's self-documenting in the README.

2025-01-23 20:01 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences/lib/util/legacy_to_async_migration_util.dart
> +/// under migrationCompletedKey in the target preferences system is not modified.
migrationCompletedKey should have brackets in both instances.

2025-01-23 20:23 UTC, stuartmorgan approved these changes
LGTM once you re-run snippet generation.

2025-01-23 21:35 UTC, tarrinneal commented
> LGTM once you re-run snippet generation.

I'm waiting for the revert pr to land before I handle conflicts and merge this pr.

2025-01-24 01:33 UTC, merged