[webview_flutter_android] Add additional WebSettings methods
flutter/packages pull request #8270
Opened 2024-12-11 09:53 UTC by westracer

Exposes native WebSettings such as setAllowFileAccess, setAllowContentAccess, setGeolocationEnabled, and setCacheMode in order to give developers more options to configure the native webview and restrict these features that are enabled by default.

Fixes [160070](https://github.com/flutter/flutter/issues/160070)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2025-01-07 22:19 UTC, bparrishMines requested changes
As I stated in https://github.com/flutter/flutter/issues/160070, I think this PR should remove support for `setCacheMode` in favor of a platform interface method. The implementation of the other methods look fine to me.

2025-01-08 10:11 UTC, westracer commented
@bparrishMines I've removed the `setCacheMode` method and I'm going to create another issue/PR for a platform interface cache behaviour method

2025-01-08 23:50 UTC, bparrishMines approved these changes
LGTM

2025-01-09 00:01 UTC, bparrishMines commented
@stuartmorgan or @flutter/android-reviewers For secondary review.

@westracer Updates to the iOS implementation is still waiting on https://github.com/flutter/packages/pull/8311 to land, so I would hold off on the iOS side of `setCacheMode` until it has.

2025-01-09 00:19 UTC, bparrishMines approved these changes

2025-01-09 00:19 UTC, bparrishMines commented on packages/webview_flutter/webview_flutter_android/CHANGELOG.md
> +* Adds WebSettings methods: `AndroidWebViewController.setAllowContentAccess` and `AndroidWebViewController.setGeolocationEnabled`.
Sorry after reviewing another PR I noticed this. I think this should be changed to

```suggestion
* Adds support for disabling content URL access within WebView and disabling the Geolocation API.
  See `AndroidWebViewController.setAllowContentAccess` and
  `AndroidWebViewController.setGeolocationEnabled`.
```

This is still ready for secondary review though.

2025-01-13 16:10 UTC, camsim99 approved these changes
LGTM :)

2025-01-13 19:06 UTC, merged