[pigeon][swift] Make `PigeonError` Class Conform to `Sendable`
flutter/packages pull request #8302
Opened 2024-12-15 07:03 UTC by bc-lee

Make `PigeonError` conform to `Sendable` for compatibility with Swift 6.0 mode by changing the `details` property type from `Any?` to `Sendable?`.

Fixes https://github.com/flutter/flutter/issues/160313

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I [linked to at least one issue that this PR fixes] in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2024-12-15 21:30 UTC, hellohuanlin commented
This will break old sdk where Sendable is undefined. You may have to put it behind a flag.

2024-12-15 21:46 UTC, bc-lee commented
> This will break old sdk where Sendable is undefined. You may have to put it behind a flag.

Are there any minimum Xcode requirements for Flutter projects? Sendable was added in Xcode 13.0 with Swift 5.5.

2024-12-15 21:59 UTC, bc-lee commented
I found the answer.  
- Flutter 3.12 or later requires Xcode 14.0 or newer.  
  [Source](https://github.com/flutter/flutter/pull/125639)  
- Flutter 3.0 or later requires Xcode 13.0 or newer.  
  [Source](https://github.com/flutter/flutter/pull/97746)  

So, I think it is safe to use this in Pigeon, as Pigeon requires Dart 3.3 and Flutter 3.19.

2024-12-19 19:11 UTC, tarrinneal requested changes

2024-12-19 19:11 UTC, tarrinneal commented on packages/pigeon/CHANGELOG.md
>  ## NEXT
This should be updated to 22.7.1 along with the pubspec version and the generator_tools file.

I guess this is technically a breaking change, so 23.0.0 might be more correct.

2024-12-19 19:11 UTC, tarrinneal commented on packages/pigeon/CHANGELOG.md
> +* [swift] Make `PigeonError` Class Conform to `Sendable`
```[swift] Changes `PigeonError` class to conform to `Sendable`.```

2024-12-19 19:13 UTC, tarrinneal commented
@stuartmorgan shouldn't this pr be failing the test exemption check?

2024-12-19 19:22 UTC, hellohuanlin approved these changes
lgtm after addressing the comments.

2024-12-26 15:55 UTC, stuartmorgan requested changes
> @stuartmorgan shouldn't this pr be failing the test exemption check?

I think there's a false negative due to the changes to generated files in `platform_tests`; we should probably tune the Cocoon rules to ignore `.gen.` files in there.

Regardless, this does need testing. A Dart unit test should be fine for this for now (although long term we probably want to adjust the Swift integration tests to actually test a flow that ensures that everything is `Sendable`)

2024-12-27 16:51 UTC, bc-lee commented
> Regardless, this does need testing. A Dart unit test should be fine for this for now (although long term we probably want to adjust the Swift integration tests to actually test a flow that ensures that everything is `Sendable`)

I have added the Dart test introduced by this PR. I also agree that the long-term solution would involve updating the Swift integration tests—not just to check for `@Sendable`, but to cover all aspects related to Swift's strict concurrency model. However, I believe this would require additional setup.

2025-01-14 22:16 UTC, tarrinneal commented
@stuartmorgan you'll need to approve this one to land it.

2025-01-21 20:09 UTC, stuartmorgan submitted a review, later dismissed

2025-01-21 20:09 UTC, stuartmorgan commented on packages/pigeon/CHANGELOG.md
> +* [swift] Changes `PigeonError` class to conform to `Sendable`.
Breaking changes need to follow the CHANGELOG style guide for breaking changes.

2025-01-21 21:38 UTC, tarrinneal commented on packages/pigeon/CHANGELOG.md
> +* [swift] Changes `PigeonError` class to conform to `Sendable`.
https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version-and-changelog-updates

2025-01-31 19:17 UTC, hellohuanlin commented on packages/pigeon/CHANGELOG.md
> +* [swift] Changes `PigeonError` class to conform to `Sendable`.
I don't think change log is accurate, because `PigeonError` already conforms to `Error`, which is by design `Sendable`. This PR does not change that. 

How about "Fixes compile error related to `PigeonError`'s sendability conformance in Swift 6 language mode"?

2025-01-31 19:23 UTC, hellohuanlin requested changes
Sorry for the block (I removed autosubmit tag), just saw the discussion on CHANGELOG and left a comment there

2025-01-31 19:25 UTC, tarrinneal commented on packages/pigeon/CHANGELOG.md
> +* [swift] Changes `PigeonError` class to conform to `Sendable`.
If it was already Sendable, why would we need to change Any? to Sendable? I'm confused.

2025-01-31 19:29 UTC, hellohuanlin commented on packages/pigeon/CHANGELOG.md
> +* [swift] Changes `PigeonError` class to conform to `Sendable`.
The `PigeonError` type itself was `Sendable`, but its `details` field was not `Sendable`, hence the compile error in Swift 6 (or compile warning in Swift 5's strict mode). 

That being said, this PR is still a breaking change tho, because the `init` signature is changed.

2025-01-31 22:07 UTC, tarrinneal commented
> Sorry for the block (I removed autosubmit tag), just saw the discussion on CHANGELOG and left a comment there: [#8302 (comment)](https://github.com/flutter/packages/pull/8302#discussion_r1937799207)

I fixed that, can you approve so we can land?

2025-01-31 22:14 UTC, hellohuanlin approved these changes

2025-01-31 22:14 UTC, hellohuanlin commented on packages/pigeon/CHANGELOG.md
> +* **Breaking Change** [swift] Fixes a compile error about PigeonError's sendability conformance in Swift 6.
```suggestion
**Breaking Change** [swift] Fixes a compile error about PigeonError's sendability conformance in Swift 6. PigeonError's init now requires the "details" argument to be Sendable.
```

2025-01-31 22:59 UTC, bc-lee commented on packages/pigeon/CHANGELOG.md
> +* [swift] Changes `PigeonError` class to conform to `Sendable`.
Sorry for the delay—I was on a national holiday.  

Yes, the above discussion is correct. `PigeonError` already conforms to `Error`, which also makes it `Sendable`. However, the type of its `details` field prevents it from conforming under Strict Concurrency, leading to a compilation error in Swift 6.

2025-02-03 18:11 UTC, tarrinneal commented
> autosubmit label was removed for flutter/packages/8302, because This PR has not met approval requirements for merging. Changes were requested by {stuartmorgan}, please make the needed changes and resubmit this PR. The PR author is not a member of flutter-hackers and needs 1 more review(s) in order to merge this PR.
> 
> * Merge guidelines: A PR needs at least one approved review if the author is already part of flutter-hackers or two member reviews if the author is not a flutter-hacker before re-applying the autosubmit label. **Reviewers**: If you left a comment approving, please use the "approve" review action instead.

@stuartmorgan not sure what the deal is here. I did "invalidate" your review since it had been addressed. Might be related.

2025-02-03 18:46 UTC, stuartmorgan approved these changes
Weird, seems like a Cocoon bug one way or another.

2025-02-03 18:47 UTC, merged