[shared_preferences] update List<String> encode/decode and other simple breaking changes
flutter/packages pull request #8335
Opened 2024-12-20 03:02 UTC by tarrinneal

Follow up to https://github.com/flutter/packages/pull/8187

fixes https://github.com/flutter/flutter/issues/124420

2025-01-03 12:26 UTC, tarrinneal commented
@stuartmorgan ready for review here as well

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  private static final String JSON_LIST_IDENTIFIER = "VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIGxpc3Qu!";
Does this need to be a very similar (and still random string) to `LIST_IDENTIFIER` if not then lets generate a new one to make it easier to tell them apart.

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  // Deprecated, for testing purposes only.
Consider using `@Deprecated`

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +        filteredPrefs.put(key, transformPref(key, Objects.requireNonNull(allPrefs.get(key))));
What was requireNonNull needed here?  Also this code is getting a bit difficult to parse. (A loop with a conditional that sets some transformed filtered data) Consider breaking parts out into methods or adding comments.

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +      if (stringValue.startsWith(JSON_LIST_IDENTIFIER)) {
I think this is where having the keys be similar starts to be important. That said from reading the code the reader does not know the keys are overlapping and it would seem safe in code review to swap the order of these if statements. 

Consider making the keys independent so that you are not relying on the contents of the keys. If that is too much code change then consider making a "LIST_PREFIX" that can be checked so that it is at least clear in code what the relationship is. 

If you want further reading see 
https://www.16elt.com/2024/09/25/first-book-of-byte-sized-tech/

I think the first example explains the principal I am applying.

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> -    } else if (value instanceof Set) {
Is this a breaking change or does the other json migration handle this now?

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/MessagesAsync.g.kt
> +  fun getStringList(key: String, options: SharedPreferencesPigeonOptions): Any?
Can we not keep the return a list of string? if not why not?

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.kt
> +const val JSON_LIST_PREFIX = "VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIGxpc3Qu!"
Does this need to be the same value as LegacySharedPreferencesPlugin? If so can you add  comment as to why and that they need to be identical? 

Same comments as above about using similar strings. I think this should be a different value entirely.

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.kt
> +  override fun getStringList(key: String, options: SharedPreferencesPigeonOptions): Any? {
Can we force cast this to a List<String>?

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.kt
> +    if (value.startsWith(JSON_LIST_PREFIX)) {
Same comment here about the hidden complexity of similar strings.

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/example/integration_test/shared_preferences_test.dart
> +        'old list encoding with getPreferences can be re-added with new encoding without data loss',
https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-newold-modifiers-in-code

 Consider instead "Non Json list encoding"

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/example/integration_test/shared_preferences_test.dart
> +          'list encoding updates to new encoding process without data loss with $backend',
https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-newold-modifiers-in-code

`list encoding updates to json encoding ...`

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/example/integration_test/shared_preferences_test.dart
> +          'old list encoding still functions with getPreferences with $backend',
same

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/example/integration_test/shared_preferences_test.dart
> +          'old list encoding with getPreferences can be re-added with new encoding without data loss with $backend',
same

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/CHANGELOG.md
> +## 3.0.0
Are the breaking changes required? if not consider fixing/mitigating the security issue independent of the breaking changes. It makes it more likely for them to be adopted.

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/lib/src/strings.dart
> +const String jsonListPrefix = 'VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIGxpc3Qu!';
This is a 3rd place where these strings are found. If they are not being generated from a file someplace consider linking to each location from every other location in a comment.

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_android.dart
> +      case 'LegacyStringListForTesting':
https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-newold-modifiers-in-code

2025-01-06 16:37 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_android.dart
> +        if (value.startsWith(listPrefix) ||
Will this list grow? if so consider making a set of prefixes to check.

2025-01-06 17:57 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/CHANGELOG.md
> +## 3.0.0
Breaking changes to `shared_preferences` have the potential to be quite disruptive to the ecosystem; I would strongly prefer we keep the legacy type support around to making a breaking change.

2025-01-06 17:57 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.kt
> +    if (value.startsWith(JSON_LIST_PREFIX)) {
I think what we want is a structure like:

```kt
if (value.startsWith(LIST_PREFIX)) {
  // The newer JSON-encoded lists use an extended prefix to distinguish them.
  if (value.startsWith(JSON_LIST_PREFIX) {
    ...
  } else {
     ...
  }
} else if (value.startsWith(DOUBLE_PREFIX)) {
  ...
```

2025-01-06 17:57 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_android.dart
> +        if (value.startsWith(listPrefix) ||
We don't generally add types to `shared_preferences` since anything that all platforms don't support ends up with unpleasant complexity like the `List<String>` mess we are currently dealing with.

2025-01-06 17:57 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
> +  /// Adds a `List<String>` to preferences using the no longer used system to test
Nit: "the no-longer-used system"

2025-01-06 19:15 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  private static final String JSON_LIST_IDENTIFIER = "VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIGxpc3Qu!";
It is meant to reduce potential breakage, but realistically it's not too likely to have conflict anyway. @stuartmorgan would you like to defend your idea here?

2025-01-06 19:18 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  private static final String JSON_LIST_IDENTIFIER = "VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIGxpc3Qu!";
I defended it [here](https://github.com/flutter/packages/pull/8335#discussion_r1904440587) instead; I still would like to do this, and have the code be clearer that this is structurally true.

2025-01-06 19:18 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +        filteredPrefs.put(key, transformPref(key, Objects.requireNonNull(allPrefs.get(key))));
It's a change suggested by a warning I was getting in Android Studio. Since the method being called requires nonnull arguments and getting a value from a map doesn't programmatically guarantee a value. In this context, there would always be a value though.

2025-01-06 19:20 UTC, reidbaker commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +      if (stringValue.startsWith(JSON_LIST_IDENTIFIER)) {
Ok I can understand that fear and why it might fail. Thank you for being open to structuring the code differently so that the overlap is easier to follow for future maintainers.

2025-01-06 19:20 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> -    } else if (value instanceof Set) {
support for Sets was removed a long time ago, this is removing legacy code for reading sets from preferences. It is a breaking change. As noted by the version bump

2025-01-06 19:22 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/MessagesAsync.g.kt
> +  fun getStringList(key: String, options: SharedPreferencesPigeonOptions): Any?
We cannot, this can now return either a list of strings, or an un-decoded string. The new way requires the string be encoded still, while the old way decoded on the platform, we cannot know which will happen in advance.

2025-01-06 19:23 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.kt
> +const val JSON_LIST_PREFIX = "VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIGxpc3Qu!"
The legacy system and the new system can both read from the same files, so we need the same prefixes

2025-01-06 19:25 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/CHANGELOG.md
> +## 3.0.0
Fair enough. I originally expected this change was going to end up being "technically" breaking due to the new prefix (before we discussed the prefix extension plan) so I wanted to wrap these long awaited breaking changes in as well. I'll revert them.

2025-01-06 19:29 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  private static final String JSON_LIST_IDENTIFIER = "VGhpcyBpcyB0aGUgcHJlZml4IGZvciBhIGxpc3Qu!";
> I defended it [here](https://github.com/flutter/packages/pull/8335#discussion_r1904440587) instead; I still would like to do this, and have the code be clearer that this is structurally true.

Sorry, I deleted my comment after I saw your other response

2025-01-06 22:25 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/CHANGELOG.md
> +## 3.0.0
> Breaking changes to `shared_preferences` have the potential to be quite disruptive to the ecosystem; I would strongly prefer we keep the legacy type support around to making a breaking change.

Should I revert the error handling changes as well?

2025-01-06 23:02 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/CHANGELOG.md
> +## 3.0.0
> Should I revert the error handling changes as well?

I did this.

2025-01-08 20:33 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/MessagesAsync.g.kt
> +  fun getStringList(key: String, options: SharedPreferencesPigeonOptions): Any?
I don't necessarily think this is a good idea, but to put it out there for consideration: we could have a `String? getJsonStringList()` and a `List<String>? getObjectEncodedStringList()`, and make the former return `''` as a sentinel value meaning "there's no JSON-encoded value, but there is an object-encoded value, so ask for that instead".

Pros:
- Strong typing.
- Separates new and legacy code more structurally.

Cons:
- Adds the complexity of understanding the sentinel value in the API flow. (We'd document it of course, but still, it's non-obvious.)
- Adds a bit of extra time to pre-conversion lookup. (I don't think this is a problem as it's only a one-time-per-legacy-value cost, but listing for completeness.)

I think I lean toward doing it for the type safety, but I'm on the fence.

2025-01-08 20:33 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.kt
> +      // lists that are encoded on the platform.
s/on the platform/using listEncoder/

2025-01-08 20:33 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
> +  Future<void> setStringListLegacyForTesting(
Generally the less test-only code in production code files the better; could we just expose `_getApiForBackend` for testing instead?

2025-01-08 20:33 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
> +    }
You can use the new pattern system to avoid the need for force unwraps and casts here:

```dart
    switch (dynamicStringList) {
      case String s:
        final String jsonEncodedString =
            s.substring(jsonListPrefix.length);
        try {
          final List<String> decodedList =
              (jsonDecode(jsonEncodedString) as List<dynamic>).cast<String>();
          return decodedList;
        } catch (e) {
          throw TypeError();
        }
      case List<Object?> l:
        return l.cast<String>().toList();
      case null:
        return null;
      default:
        throw TypeError();
    }
```

2025-01-08 20:33 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
> +          (value! as String).startsWith(jsonListPrefix)) {
`if (value is String && value.startsWith(jsonListPrefix)`. (Using `is` will implicitly convert for the remainder of the block.)

2025-01-08 20:33 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
> +            (jsonDecode((value as String).substring(jsonListPrefix.length))
You'll be able to replace `(value as String)` with just `value` here as well.

2025-01-08 20:33 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
> +                .toList();
I don't think `toList()` should be necessary here.

2025-01-09 20:52 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/MessagesAsync.g.kt
> +  fun getStringList(key: String, options: SharedPreferencesPigeonOptions): Any?
There's a third less complex, somewhat stupid, but maybe better solution...

get String
decode
re-encode into json
send to dart
decode
profit

2025-01-10 16:13 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/kotlin/io/flutter/plugins/sharedpreferences/MessagesAsync.g.kt
> +  fun getStringList(key: String, options: SharedPreferencesPigeonOptions): Any?
I thought of that, but then we have two different copies of the code to encode into JSON, in two different languages, which seemed potentially worse. I'm not sure how much Java code that is though; maybe it's so little it doesn't matter.

2025-01-14 19:20 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
> +  Future<void> setStringListLegacyForTesting(
I'm not sure I understand this suggestion, are you saying I should add an option in that method that sets which version of setString is used?

2025-01-14 19:23 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_async_android.dart
> +          (value! as String).startsWith(jsonListPrefix)) {
I always forget about is

2025-01-23 20:18 UTC, stuartmorgan requested changes

2025-01-23 20:18 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  private static final String JSON_LIST_IDENTIFIER = LIST_IDENTIFIER + "!";
I think it's worth a comment that `!` is chosen as a character that can't be created by the base 64 encoding used with `LIST_IDENTIFIER`.

2025-01-23 20:18 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
Couldn't we eliminate this method from the Pigeon protocol and just change the `setString` check to `((value.startsWith(LIST_IDENTIFIER) && ! value.startsWith(JSON_LIST_IDENTIFIER) || ...`? Since the structure of the new design is that the Dart code is responsible for encoding it to just be a string, it seems odd to have a dedicated setter for that string.

2025-01-23 20:18 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/lib/src/shared_preferences_android.dart
> +      case 'PlatformEncodedStringListForTesting':
This could also be eliminated by exposing a way for tests to get `_api`.

2025-01-23 21:46 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
we could, but then the method could be used to add a string with that json list identifier, which is the whole point of the check.

I could move the check for that one prefix to dart though, that is what you think is best.

2025-01-24 17:59 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
Ah, right. I guess this is fine then.

Ideally what we would do is move all of the prefixing logic to Dart; the weirdness here is because we're now doing some special casing in native code, and some in Dart. But that's more refactoring than this PR needs.

2025-01-24 17:59 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/pigeons/messages.dart
> +  bool setStringList(String key, String value);
Let's at least call this `setPreEncodedStringList` or something, so it's clear why it's called string list but takes a `String`.

2025-01-24 18:00 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
Yeah, I don't love it. Moving the checks without updating the error type seems silly.

2025-01-24 18:03 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
I've done it in some other plugins, with a comment explaining why I'm throwing a weird `PlatformException` from Dart. It's a different kind of odd, but I don't think it's silly, since it allows us to make progress on moving logic to Dart, which in many cases makes our lives easier, without gating it behind breaking changes.

2025-01-24 18:09 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
I had considered it, I can add it to this pr if you want. I don't think it's a big deal

2025-01-24 18:33 UTC, stuartmorgan approved these changes
LGTM

2025-01-24 18:34 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
Let's leave refactoring the existing logic to future work if we find that we are changing this enough to warrant the time.

2025-01-24 18:54 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
ok, for my understanding though. Is this error I wrote:
```
PlatformException(java.lang.RuntimeException: StorageError: This string cannot be stored as it
clashes with special identifier prefixes, RuntimeException, Cause: null, Stacktrace:
java.lang.RuntimeException: StorageError: This string cannot be stored as it clashes with special
identifier prefixes, null)
```
similar enough to 
```
PlatformException(java.lang.RuntimeException: StorageError: This string cannot be stored as it
clashes with special identifier prefixes, RuntimeException, Cause: null, Stacktrace:
java.lang.RuntimeException: StorageError: This string cannot be stored as it clashes with special
identifier prefixes
        at
io.flutter.plugins.sharedpreferences.LegacySharedPreferencesPlugin.setString(LegacySharedPreferencesPlugin.java:83)
        at
io.flutter.plugins.sharedpreferences.Messages$SharedPreferencesApi$-CC.lambda$setUp$2(Messages.java:204)
        at
io.flutter.plugins.sharedpreferences.Messages$SharedPreferencesApi$$ExternalSyntheticLambda2.onMessage(D8$$SyntheticClass:0)
        at
io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
        at
io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
        at
io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
        at
io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0$io-flutter-embedding-engine-dart-DartMessenger$SerialTaskQueue(DartMessenger.java:163)
        at
io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
, null)
```?

2025-01-24 18:55 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
I don't think I can replicate the entire stack trace reliably

2025-01-24 19:32 UTC, stuartmorgan commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
Yes, if someone is relying on the format of the stack trace, they are going to have a bad time. The important things to preserve are:
- code, since that's the most likely thing for someone to match on, and
- message, which is debatable, and depends a lot on the code; some of our plugins use the same code for everything so people trying to distinguish have, for lack of a better option, done string matching on the message, so in those cases I try to preserve the message too.

2025-01-24 19:48 UTC, tarrinneal commented on packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/LegacySharedPreferencesPlugin.java
> +  public @NonNull Boolean setStringList(@NonNull String key, @NonNull String value)
Another important thing to note is that this error suffers from the pigeon error code swapping issue as well. (I couldn't find the filed issue to link)

2025-01-24 21:23 UTC, merged

2025-01-25 16:38 UTC, stuartmorgan commented
It looks like this may have caused OOB failure in `shared_preferences` tests when it was published.

2025-01-27 17:30 UTC, camsim99 commented
This is causing `shared_preferences/shared_preferences/example/integration_test/shared_preferences_test.dart: shared_preferences_async Async throws TypeError when returned getStringList type is incorrect` to fail with what looks like an OOB issue and is blocking the tree currently:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test (but after the test had completed):
Expected: throws <Instance of 'TypeError'>
  Actual: <Closure: () => Future<Null>>
   Which: returned a Future that emitted <null>

When the exception was thrown, this was the stack:
#0      fail (package:matcher/src/expect/expect.dart:149:31)
#1      _expect.<anonymous closure> (package:matcher/src/expect/expect.dart:125:9)
<asynchronous suspension>
<asynchronous suspension>
(elided 6 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

The plan is to revert.