[video_player]: add setVideoPositionUpdatesInterval method to allow setting position updates periodic intervals
flutter/packages pull request #8346
Opened 2024-12-26 04:12 UTC by abdelaziz-mahdy

Description
This PR introduces a new method, setVideoPositionUpdatesInterval, to the VideoPlayerController class. This method allows developers to dynamically set the periodic duration for video position updates. The periodic timer previously had a fixed interval of 500 milliseconds, which could lead to delays in scenarios such as subtitle synchronization. With this change, developers can adjust the timer interval as needed, improving flexibility and user experience.

Before: The position updates were locked to a 500-millisecond interval, causing potential delays and inconsistent behavior, particularly with fast-changing elements like subtitles.

After: Developers can now specify a custom interval for position updates using the new setVideoPositionUpdatesInterval method. The timer is restarted dynamically with the new interval to ensure seamless updates.

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/160855
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran the auto-formatter. (Unlike the flutter/flutter repo, the flutter/packages repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the package surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I [linked to at least one issue that this PR fixes] in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style], or this PR is [exempt from CHANGELOG changes].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[relevant style guides]: https://github.com/flutter/packages/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[linked to at least one issue that this PR fixes]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#version
[following repository CHANGELOG style]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style
[exempt from CHANGELOG changes]: https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests

2024-12-26 15:47 UTC, stuartmorgan commented
Per discussion linked from https://github.com/flutter/flutter/issues/90080#issuecomment-1971463891 I'm skeptical that this is API we want to add. If subtitles don't work reliably at the current update frequency, and higher update frequencies don't have noticeable performance impact, then we should simply increase the frequency. If it does have performance issues, then we should figure out a different way of triggering subtitle changes. Either way, I would expect that we should be able to resolve the issue without new public API and without requiring extra configuration.

2024-12-26 16:39 UTC, abdelaziz-mahdy commented
I kept searching for the previous discussions but couldn't find them. Thank you for providing the link.

Would an update frequency of 100ms work? I think it would be very effective for subtitles and not frequent enough to cause a high load on devices.

if you agree, i can open a new pr with that change and add a test to make sure captions are included in the timer consideration

2024-12-26 17:01 UTC, abdelaziz-mahdy commented
note: this is how i override it from the app side, i didnt like the approach this is why i opened this pr
```
  void startPositionUpdaterForcer() {
    _positionUpdaterForcerTimer?.cancel();
    _positionUpdaterForcerTimer =
        Timer.periodic(Duration(milliseconds: 100), (timer) {
      _positionUpdaterForcer();
    });
  }

  void stopPositionUpdaterForcer() {
    _positionUpdaterForcerTimer?.cancel();
  }
  /// These parts exists in the video_player package but slightly edited to be called from outside of the class
  Future<void> _positionUpdaterForcer() async {
    Duration? position = await controller.position;
    if (position == null) {
      return;
    }
    VideoPlayerValue value = controller.value;
    if (position > value.duration) {
      position = value.duration;
    }
    value = value.copyWith(
      position: position,
      caption: await _getCaptionAt(position),
      isCompleted: position == value.duration,
    );
  }

  Future<Caption> _getCaptionAt(Duration position) async {
    /// the internal [ClosedCaptionFile]
    ClosedCaptionFile? closedCaptionFile;
    closedCaptionFile = await controller.closedCaptionFile;
    if (closedCaptionFile == null) {
      return Caption.none;
    }

    VideoPlayerValue value = controller.value;
    final Duration delayedPosition = position + value.captionOffset;
    // TODO(johnsonmh): This would be more efficient as a binary search.
    for (final Caption caption in (closedCaptionFile).captions) {
      if (caption.start <= delayedPosition && caption.end >= delayedPosition) {
        return caption;
      }
    }

    return Caption.none;
  }
```

2024-12-28 02:21 UTC, abdelaziz-mahdy commented
i updated the pr to be an update to value from 500 to 100 ms, and the test case. hope thats okay

2025-02-10 17:48 UTC, stuartmorgan requested changes

2025-02-10 17:48 UTC, stuartmorgan commented on packages/video_player/video_player/CHANGELOG.md
> +* Added `setVideoPositionUpdatesInterval` to allow setting position updates periodic intervals
Adds

https://github.com/flutter/flutter/blob/master/docs/ecosystem/contributing/README.md#changelog-style

2025-02-10 17:48 UTC, stuartmorgan commented on packages/video_player/video_player/CHANGELOG.md
> +* Added `setVideoPositionUpdatesInterval` to allow setting position updates periodic intervals
This is also missing a period, also per the style guide.

2025-02-10 17:48 UTC, stuartmorgan commented on packages/video_player/video_player/CHANGELOG.md
> +* Added `setVideoPositionUpdatesInterval` to allow setting position updates periodic intervals
And it needs to be rewritten to reflect what the change now does; this is describing the previous iteration of the PR.

2025-02-10 17:48 UTC, stuartmorgan commented on packages/video_player/video_player/test/video_player_test.dart
> +  test('updates position', () async {
There should be a blank line between tests/groups.

2025-02-10 17:48 UTC, stuartmorgan commented on packages/video_player/video_player/test/video_player_test.dart
> +    // Set a custom interval
This no longer makes sense.

2025-02-10 17:48 UTC, stuartmorgan commented on packages/video_player/video_player/test/video_player_test.dart
> +    expect(positions[1] - positions[0], greaterThanOrEqualTo(customInterval));
Wouldn't this test as written pass without the rest of the PR?

2025-02-10 22:41 UTC, abdelaziz-mahdy commented on packages/video_player/video_player/CHANGELOG.md
> +* Added `setVideoPositionUpdatesInterval` to allow setting position updates periodic intervals
thanks for the link, it should fit now

2025-02-10 22:44 UTC, abdelaziz-mahdy commented on packages/video_player/video_player/test/video_player_test.dart
> +    expect(positions[1] - positions[0], greaterThanOrEqualTo(customInterval));
just tested using 500 ms for the updates and it failed, but i will add another test related to the captions since its the more related to this pr

2025-02-10 23:03 UTC, abdelaziz-mahdy commented on packages/video_player/video_player/test/video_player_test.dart
> +    expect(positions[1] - positions[0], greaterThanOrEqualTo(customInterval));
I added the other test and I hope its shows the problem more, let me know if there anything else I can fix.

Thank you.

2025-03-07 19:09 UTC, stuartmorgan approved these changes
LGTM with one change. @tarrinneal for second review.

2025-03-07 19:09 UTC, stuartmorgan commented on packages/video_player/video_player/test/video_player_test.dart
> +    await intervalUpdateCompleter.future.timeout(const Duration(seconds: 5));
Tests should not include timeouts, per Flutter style. This should just await the future.

2025-03-17 21:00 UTC, tarrinneal approved these changes
lgtm, with some clarity in the changelog.

2025-03-17 21:00 UTC, tarrinneal commented on packages/video_player/video_player/CHANGELOG.md
> +* Reduces the update interval from 500ms to 100ms.
I think this should be clearer about what update interval is changing

2025-03-17 21:03 UTC, abdelaziz-mahdy commented on packages/video_player/video_player/CHANGELOG.md
> +* Reduces the update interval from 500ms to 100ms.
thank you, I hope its more clear now.

2025-03-18 17:08 UTC, stuartmorgan commented
This is hitting the known camerax flake; it's unrelated to the PR.

2025-03-18 18:46 UTC, merged